package com.mnrclara.api.management.model.matterexpense;

import java.util.Date;

public interface IMatterExpense {
	
	public Long getMatterExpenseId();
	public Double getNumberOfItems();
	public Double getExpenseAmount();
	public String getLanguageId();
	public String getClassId();
	public String getMatterNumber();
	public String getCaseInformationNo();
	public String getClientId();
	public String getExpenseCode();
	public String getCaseCategoryId();
	public String getCaseSubCategoryId();
	public String getCostPerItem();
	public String getNumberofItems();
	public String getRateUnit();
	public String getExpenseDescription();
	public String getExpenseType();
	public String getBillType();
	public String getWriteOff();
	public String getExpenseAccountNumber();
	public String getStatusId();
	public String getDeletionIndicator();
	public String getReferenceField1();
	public String getSReferenceField2();
	public Date getReferenceField2();
	public String getReferenceField3();
	public String getReferenceField4();
	public String getReferenceField5();
	public String getReferenceField6();
	public String getReferenceField7();
	public String getReferenceField8();
	public String getReferenceField9();
	public String getReferenceField10();
	public String getCreatedBy();
	public Date getCreatedOn();
	public String getSCreatedOn();
	public String getUpdatedBy();
	public Date getUpdatedOn();
	public String getSUpdatedOn();
	public String getBillableToClient();
	public String getCardNotAccepted();
	public String getPayableTo();
	public String getPaymentMode();
	public String getSRequiredDate();
	public Date getRequiredDate();
	public String getVendorFax();
	public String getVendorMailingAddress();
	public String getVendorNotes();
	public String getVendorPhone();
	public String getUserName();
	public String getQbDepartment();
	public String getCheckRequestStatus();
	public String getDocumentName();
	public String getPhysicalCard();
	public String getCreditCard();
	public Date getExpirationDate();
	public String getSExpirationDate();
	public String getNameOnCardOrCheck();
	public String getSecurityCode();
	public String getTypeOfCreditCard();
	public String getCheckRequestCreatedBy();
	public Date getCheckRequestCreatedOn();
	public String getSCheckRequestCreatedOn();
}