
server.port=9296

server.servlet.context-path=/overc

spring.datasource.url=jdbc:sqlserver://3.7.14.236;databaseName=AG01_DB2
spring.datasource.username=sa
spring.datasource.password=jbtM1nw013W6vOAtmRx
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=false
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jackson.time-zone=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#-----------Batch Configurtion-------------------------------------
spring.batch.initialize-schema=always
spring.batch.job.enabled=false
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB


#security
security.oauth2.resource.filter-order=3

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.protocol=smtp
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=no-reply@overc360.com
spring.mail.password=N&381892577758un
