package com.courier.overc360.api.model.transaction;


import lombok.Data;

import javax.persistence.Column;
import java.util.Date;
import java.util.List;
import java.util.Set;

@Data
public class AddConsignment {

    private Long consignmentId;
    private String languageId;
    private String languageDescription;
    private String companyId;
    private String companyName;
    private String statusId;
    private String statusDescription;
    private String partnerId;
    private String partnerType;
    private String partnerName;
    private String masterAirwayBill;
    private String houseAirwayBill;
    private String noOfPieceHawb;
    private String partnerMasterAirwayBill;
    private String partnerHouseAirwayBill;
    private String productId;
    private String productName;
    private String subProductId;
    private String subProductName;
    private String serviceTypeId;
    private String serviceTypeText;
    private String shipperId;
    private String shipperName;
    private String noOfPackageMawb;
    private String noOfPackageHawb;
    private String flightNo;
    private String lineNo;
    private String flightName;
    private Date flightArrivalTime;
    private String countryOfSupply;
    private String remark;
    private String currency;
    private String invoiceAmount;
    private Double declaredValue;
    private String consignmentCurrency;
    private Double consignmentValue;
    private String actualCurrency;
    private Double totalDuty;
    private Long consignmentBagId;
    private Double consignmentValueLocal;
    private Double addIata;
    private Double addInsurance;
    private Double customsValue;
    private Double calculatedTotalDuty;
    private String countryOfDestination;
    private Date estimatedDepartureTime;
    private String airportOriginCode;
    private String airportDestinationCode;
    private String invoiceName;
    private String invoiceNumber;
    private Date invoiceDate;
    private String invoiceType;
    private String invoiceUrl;
    private Double volume;
    private String incoTerms;
    private String hsCode;
    private String goodsDescription;
    private String countryOfOrigin;
    private String manufacturer;
    private String noOfPackages;
    private String quantity;
    private Double netWeight;
    private Double grossWeight;
    private String isExempted;
    private String customerCode;
    private String customerReferenceNumber;
    private String hubCode;
    private String hubName;
    private String pieceId;
    private String consignmentType;
    private String actionType;
    private String movementType;
    private String forwardReferenceNumber;
    private String paymentType;
    private String eventCode;
    private String eventText;
    private Date eventTimestamp;
    private Date statusTimestamp;
    private String primaryDo;
    private Double exchangeRate;
    private String customsCurrency;
    private String dutyPercentage;
    private Double iataCharge;
    private String dduCharge;
    private Double specialApprovalCharge;
    private String secondaryDo;
    private Long consoleIndicator;
    private Long manifestIndicator;
    private String modeOfTransport;
    private String insurance;
    private String loadTypeId;
    private String loadType;
    private String description;
    private String notes;
    private String codAmount;
    private String codFavorOf;
    private String codCollectionMode;
    private String declaredValueWithoutTax;
    private Double length;
    private String dimensionUnit;
    private Double width;
    private Double height;
    private Double weight;
    private String weightUnit;
    private String volumeUnit;
    private String priority;
    private String courierPartner;
    private String courierAccount;
    private String courierPartnerReferenceNumber;
    private String pickupOtp;
    private String deliveryOtp;
    private String rtoOtp;
    private String tags;
    private String serviceTime;
    private String pickupServiceTime;
    private String deliveryServiceTime;
    private String pickupTimeSlotStart;
    private String pickupTimeSlotEnd;
    private String scheduledAt;
    private String ewayBill;
    private String productCode;
    private String amount;
    private String isCustomsDeclarable;
    private String exemptionFor;
    private String exemptionBeneficiary;
    private String exemptionReference;
    private String packDetails;
    private String storageLocation;
    private String storageDescription;
    private String isExchange;
    private String reverseReason;
    private String hawbType;
    private String hawbTypeId;
    private String hawbTypeDescription;
    private Date hawbTimeStamp = new Date();
    private Double clearanceCharge;
    private Double handlingFees;
    private Double foodApprovals;
    private Double otherApprovals;
    private Double nasDelivery;
    private Double global;
    private Double approval;
    private Double handlingFork;
    private Double stampCharges;
    private String zoneId;
    private String zoneText;
    private String zoneType;
    private Double actualWeight;
    private Double ceilingValue;
    private Double chargeableWeight;
    private Double frightCharge;
    private Double codCharge;
    private Double fulfilmentCharge;
    private Double rtoCharge;
    private Double asrCharge;
    private Double movementCharge;
    private Double truckCharge;
    private Double paymentCollected;
    private Double totalLmdCharges;
    private Double outboundClearance;
    private String referenceField1;
    private String referenceField2;
    private String referenceField3;
    private String referenceField4;
    private String referenceField5;
    private String referenceField6;
    private String referenceField7;
    private String referenceField8;
    private String referenceField9;
    private String referenceField10;
    private String addDestinationDetails;
    private String addOriginDetails;
    private String address;
    private String destinations;
    private Long pickupEntityId;
    private Long deletionIndicator = 0L;
    private String createdBy;
    private Date createdOn = new Date();
    private String updatedBy;
    private Date updatedOn = new Date();
    private Long preAlertValidationIndicator;
    private AddDestinationDetails destinationDetails;
    private AddOriginDetails originDetails;
    private AddReturnDetails returnDetails;
    private List<AddPieceDetails> pieceDetails;
    private Set<AddImageReference> referenceImageList ;

}
