-- Master ID Scripts
-- Database
USE WMS;

-- LANGUAGE ID Table
CREATE TABLE `WMS`.`tbllanguageid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `LANG_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`LANG_ID`))
COMMENT = 'LANGUAGE ID';

-- Vertical ID Table
CREATE TABLE `WMS`.`tblverticalid` (
  `VERT_ID` INT NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `VERTICAL` NVARCHAR(50) NULL,
  `REMARK` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`VERT_ID`, `LANG_ID`))
COMMENT = 'Vertical ID';

-- Currency ID Table
CREATE TABLE `WMS`.`tblcurrencyid` (
  `CURR_ID` NVARCHAR(10) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CURR_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`CURR_ID`, `LANG_ID`))
COMMENT = 'Currency ID';
	
-- Company ID Table
CREATE TABLE `WMS`.`tblcompanyid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `C_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `LANG_ID`))
COMMENT = 'Company ID';

-- Warehouse ID Table
CREATE TABLE `WMS`.`tblwarehouseid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `WH_ID`, `LANG_ID`, `PLANT_ID`))
COMMENT = 'Warehouse ID';

-- Plant ID Table
CREATE TABLE `WMS`.`tblplantid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `PLANT_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`,`PLANT_ID`,`LANG_ID`))
COMMENT = 'Plant ID';

-- Floor ID Table
CREATE TABLE `WMS`.`tblfloorid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `FL_ID` NVARCHAR(50)  NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `FL_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `FL_ID`,`LANG_ID`))
COMMENT = 'Floor ID';

-- Storage Section ID Table
CREATE TABLE `WMS`.`tblstoragesectionid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `FL_ID` NVARCHAR(50)  NOT NULL,
  `ST_SEC_ID` NVARCHAR(5) NOT NULL,
  `ST_SEC` NVARCHAR(50) NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `ST_SEC_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `FL_ID`, `ST_SEC_ID`, `LANG_ID`))
COMMENT = 'Storage Section ID';
		
-- Row ID Table
CREATE TABLE `WMS`.`tblrowid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `FL_ID` NVARCHAR(50)  NOT NULL,
  `ST_SEC_ID` NVARCHAR(10) NOT NULL,
  `ROW_ID` NVARCHAR(10) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `ROW_TEXT` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `FL_ID`, `ST_SEC_ID`, `ROW_ID`, `LANG_ID`))
COMMENT = 'Row ID';

-- Aisle ID Table
CREATE TABLE `WMS`.`tblaisleid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `FL_ID` NVARCHAR(50)  NOT NULL,
  `ST_SEC_ID` NVARCHAR(10) NOT NULL,
  `AISLE_ID` NVARCHAR(10) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `AISLE_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `FL_ID`, `ST_SEC_ID`, `AISLE_ID`, `LANG_ID`))
COMMENT = 'Aisle ID';

-- Span ID Table
CREATE TABLE `WMS`.`tblspanid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `FL_ID` NVARCHAR(50)  NOT NULL,
  `ST_SEC_ID` NVARCHAR(10) NOT NULL,
  `AISLE_ID` NVARCHAR(10) NOT NULL,
  `ROW_ID` NVARCHAR(10) NOT NULL,
  `SPAN_ID` NVARCHAR(10) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `SPAN_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `FL_ID`, `ST_SEC_ID`, `AISLE_ID`,`ROW_ID`,`SPAN_ID`, `LANG_ID`))
COMMENT = 'Span ID';

-- Shelf ID Table
CREATE TABLE `WMS`.`tblshelfid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `FL_ID` NVARCHAR(50)  NOT NULL,
  `ST_SEC_ID` NVARCHAR(10) NOT NULL,
  `AISLE_ID` NVARCHAR(10) NOT NULL,
  `ROW_ID` NVARCHAR(10) NOT NULL,
  `SPAN_ID` NVARCHAR(10) NOT NULL,
  `SHELF_ID` NVARCHAR(10) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `SHELF_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `FL_ID`, `ST_SEC_ID`, `AISLE_ID`,`ROW_ID`,`SPAN_ID`, `SHELF_ID`, `LANG_ID`))
COMMENT = 'Shelf ID';

-- Storage Class ID Table
CREATE TABLE `WMS`.`tblstorageclassid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ST_CL_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `ST_CL_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `ST_CL_ID`, `LANG_ID`))
COMMENT = 'Storage Class ID';

-- Storage Type ID Table
CREATE TABLE `WMS`.`tblstoragetypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ST_CL_ID` INTEGER NOT NULL,
  `ST_TYP_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `ST_TYP_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `ST_CL_ID`, `ST_TYP_ID`, `LANG_ID`))
COMMENT = 'Storage Type ID';

-- Storage Bin Type ID Table
CREATE TABLE `WMS`.`tblstoragebintypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ST_CL_ID` INTEGER NOT NULL,
  `ST_TYP_ID` INTEGER NOT NULL,
  `ST_BIN_TYP_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `ST_BIN_TYP_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `ST_CL_ID`, `ST_TYP_ID`, `ST_BIN_TYP_ID`, `LANG_ID`))
COMMENT = 'Storage Bin Type ID';

-- Door ID Table
CREATE TABLE `WMS`.`tbldoorid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `DOOR_ID` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `DOOR_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `DOOR_ID`, `LANG_ID`))
COMMENT = 'Door ID';

-- Process ID Table
CREATE TABLE `WMS`.`tblprocessid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `PROCESS_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `PROCESS` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `PROCESS_ID`, `LANG_ID`))
COMMENT = 'Process ID';

-- User Type ID Table
CREATE TABLE `WMS`.`tblusertypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `USR_TYP_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `USR_TYP_TEXT` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `USR_TYP_ID`, `LANG_ID`))
COMMENT = 'User Type ID';

-- UOM ID Table
CREATE TABLE `WMS`.`tbluomid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `UOM_ID` NVARCHAR(10) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `UOM_TEXT` NVARCHAR(50) NULL,
  `UOM_TYP` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `UOM_ID`, `LANG_ID`))
COMMENT = 'UOM ID';

-- Module ID Table
CREATE TABLE `WMS`.`tblmoduleid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `MOD_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `MODULE_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`,`MOD_ID`,`LANG_ID`))
COMMENT = 'Module ID';

-------------------------------------------------------------------------------------------------------------
-- Adhoc Module ID Table
CREATE TABLE `WMS`.`tbladhocmoduleid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `MOD_ID` INTEGER NOT NULL,
  `ADHOC_MOD_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `ADHOC_MODULE_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`,`MOD_ID`,`ADHOC_MOD_ID`, `LANG_ID`))
COMMENT = 'Adhoc Module ID';

-- Level Id Table
CREATE TABLE `WMS`.`tbllevelid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `LEVEL_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `LEVEL` NVARCHAR(50) NOT NULL,
  `LEVEL_REF` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`,`LEVEL_ID`,`LANG_ID`,`LEVEL`))
COMMENT = 'Level Id';

-- Palletization Level ID Table
CREATE TABLE `WMS`.`tblpalletizationlevelid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `PAL_LVL_ID` INTEGER NOT NULL,
  `PAL_LVL` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `PAL_LVL_REF` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `PAL_LVL_ID`, `PAL_LVL`, `LANG_ID`))
COMMENT = 'Palletization Level ID';

-- Approval Process ID Table
CREATE TABLE `WMS`.`tblapprovalprocessid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `APP_PROCESS_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `APP_PROCESS` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`,`APP_PROCESS_ID`, `LANG_ID`))
COMMENT = 'Approval Process ID';

-- Barcode Subtype ID Table
CREATE TABLE `WMS`.`tblbarcodesubtypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `BAR_TYP_ID` INTEGER NOT NULL,
  `BAR_SUB_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `BAR_SUB_TYP` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `BAR_TYP_ID`, `BAR_SUB_ID`, `LANG_ID`))
COMMENT = 'Barcode Subtype ID';

-- Barcode Type ID Table
CREATE TABLE `WMS`.`tblbarcodetypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `BAR_TYP_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `BAR_TYP` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `BAR_TYP_ID`, `LANG_ID`))
COMMENT = 'Barcode Type ID';

-- Employee ID Table
CREATE TABLE `WMS`.`tblemployeeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `EMP_ID` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `EMP_NM` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`,`EMP_ID`, `LANG_ID`))
COMMENT = 'Employee ID';

-- Strategy ID Table
CREATE TABLE `WMS`.`tblstrategyid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `STR_TYP_ID` INTEGER NOT NULL,
  `ST_NO` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `STR_TYP_TEXT` NVARCHAR(50) NULL,
  `ST_NO_TEXT` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`,`STR_TYP_ID`, `ST_NO`, `LANG_ID`))
COMMENT = 'Strategy ID';

-- Menu ID Table
CREATE TABLE `WMS`.`tblmenuid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `MENU_ID` INTEGER NOT NULL,
  `SUB_MENU_ID` INTEGER NOT NULL,
  `AUT_OBJ_ID` INTEGER NOT NULL,
  `AUT_OBJ_VALUE` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `MENU_TEXT` NVARCHAR(50) NULL,
  `SUB_MENU_TEXT` NVARCHAR(50) NULL,
  `AUT_OBJ` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `MENU_ID`, `SUB_MENU_ID`, `AUT_OBJ_ID`, `AUT_OBJ_VALUE`,`LANG_ID`))
COMMENT = 'Menu ID';

-- BIN Section ID Table
CREATE TABLE `WMS`.`tblbinsectionid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `BIN_SECTION_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `BIN_SEC` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`,`BIN_SECTION_ID`, `LANG_ID`))
COMMENT = 'BIN Section ID';

-- Date Format ID Table
CREATE TABLE `WMS`.`tbldateformatid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `DATE_FOR_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `DATE_FORMAT` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`,`DATE_FOR_ID`, `LANG_ID`))
COMMENT = 'Date Format ID';

-- Decimal Notation ID Table
CREATE TABLE `WMS`.`tbldecimalnotationid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `DEC_NOT_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `DECIMAL_NOTATION` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`,`DEC_NOT_ID`, `LANG_ID`))
COMMENT = 'Decimal Notation ID';

-- Status Messages ID Table
CREATE TABLE `WMS`.`tblstatusmessagesid` (
  `MESSAGE_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `MESSAGE_TYP` NVARCHAR(50) NOT NULL,
  `MESSAGE_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`MESSAGE_ID`,`LANG_ID`,`MESSAGE_TYP`))
COMMENT = 'Status Messages ID';

-- Warehouse Type ID Table
CREATE TABLE `WMS`.`tblwarehousetypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `WH_TYP_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `WH_TYP_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `WH_TYP_ID`, `LANG_ID`))
COMMENT = 'Warehouse Type ID';

-- Movement Type ID Table
CREATE TABLE `WMS`.`tblmovementtypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `MVT_TYP_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `MVT_TYP_TEXT` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `MVT_TYP_ID`, `LANG_ID`))
COMMENT = 'Movement Type ID';

-- Sub Movement TypeID Table
CREATE TABLE `WMS`.`tblsubmovementtypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `MVT_TYP_ID` INTEGER NOT NULL,
  `SUB_MVT_TYP_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `SUB_MVT_TYP` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `MVT_TYP_ID`, `SUB_MVT_TYP_ID`, `LANG_ID`))
COMMENT = 'Sub Movement Type ID';

-- Transfer Type ID Table
CREATE TABLE `WMS`.`tbltransfertypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `TR_TYP_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `TR_TYP_TEXT` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `TR_TYP_ID`, `LANG_ID`))
COMMENT = 'Transfer Type ID';

-- Stock Type ID Table
CREATE TABLE `WMS`.`tblstocktypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `STCK_TYP_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `STCK_TYP_TEXT` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `STCK_TYP_ID`, `LANG_ID`))
COMMENT = 'Stock Type ID';

-- Special Stock Indicator ID Table
CREATE TABLE `WMS`.`tblspecialstockindicatorid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `STCK_TYP_ID` INTEGER NOT NULL,
  `SP_ST_IND_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `SP_ST_IND_TEXT` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `STCK_TYP_ID`,`SP_ST_IND_ID`, `LANG_ID`))
COMMENT = 'Special Stock Indicator ID';

-- Handling Equipment ID Table
CREATE TABLE `WMS`.`tblhandlingequipmentid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `HE_ID` INTEGER NOT NULL,
  `HE_NO` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `HE_NO_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `HE_ID`, `HE_NO`, `LANG_ID`))
COMMENT = 'Handling Equipment ID';

-- Handling Unit ID Table
CREATE TABLE `WMS`.`tblhandlingunitid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `HU_ID` INTEGER NOT NULL,
  `HU_NO` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `HU_NO_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `HU_ID`, `HU_NO`, `LANG_ID`))
COMMENT = 'Handling Unit ID';

-- Dock ID Table
CREATE TABLE `WMS`.`tbldockid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `DK_ID` NVARCHAR(10) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL, 
  `DK_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `DK_ID`, `LANG_ID`))
COMMENT = 'Dock ID';

-- Work Center ID Table
CREATE TABLE `WMS`.`tblworkcenterid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `WRK_CTR_ID` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `WRK_CTR_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `WRK_CTR_ID`, `LANG_ID`))
COMMENT = 'Work Center ID';

-- Cycle Count Type ID Table
CREATE TABLE `WMS`.`tblcyclecounttypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `CC_TYP_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `CC_TYP_TEXT` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `CC_TYP_ID`, `LANG_ID`))
COMMENT = 'Cycle Count Type ID';

-- Return Type ID Table
CREATE TABLE `WMS`.`tblreturntypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `RETURN_TYP_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `RETURN_TYP_TEXT` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `RETURN_TYP_ID`, `LANG_ID`))
COMMENT = 'Return Type ID';

-- Outbound Order type ID Table
CREATE TABLE `WMS`.`tbloutboundordertypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `OB_ORD_TYP_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `OB_ORD_TYP_TEXT` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `OB_ORD_TYP_ID`, `LANG_ID`))
COMMENT = 'Outbound Order type ID';

-- Outbound Order status ID Table
CREATE TABLE `WMS`.`tbloutboundorderstatusid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `OB_ORD_STATUS_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `OB_ORD_STATUS_TEXT` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `OB_ORD_STATUS_ID`, `LANG_ID`))
COMMENT = 'Outbound Order status ID';

-- Inbound Order type ID Table
CREATE TABLE `WMS`.`tblinboundordertypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `IB_ORD_TYP_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `IB_ORD_TYP` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `IB_ORD_TYP_ID`, `LANG_ID`))
COMMENT = 'Inbound Order type ID';

-- Inbound Order status ID Table
CREATE TABLE `WMS`.`tblinboundorderstatusid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `IB_ORD_STATUS_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `IB_ORD_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `IB_ORD_STATUS_ID`, `LANG_ID`))
COMMENT = 'Inbound Order status ID';

-- Bin Class ID Table
CREATE TABLE `WMS`.`tblbinclassid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `BIN_CL_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `BIN_CLASS` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `BIN_CL_ID`, `LANG_ID`))
COMMENT = 'Bin Class ID';

-- Control type ID Table
CREATE TABLE `WMS`.`tblcontroltypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `CTRL_TYP_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL, 
  `CTRL_TYP` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `CTRL_TYP_ID`, `LANG_ID`))
COMMENT = 'Control type ID';

-- Approval ID Table
CREATE TABLE `WMS`.`tblapprovalid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `APP_PROCESS_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `APP_LVL` NVARCHAR(50) NOT NULL,
  `APP_CODE` NVARCHAR(50) NOT NULL,
  `APP_PROCESS` NVARCHAR(50) NULL,
  `APP_NM` NVARCHAR(50) NULL,
  `DESIGNATION` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `APP_PROCESS_ID`, `LANG_ID`,`APP_LVL`, `APP_CODE`))
COMMENT = 'Approval ID';

-- Country ID Table
CREATE TABLE `WMS`.`tblcountryid` (
  `COUNTRY_ID` NVARCHAR(10) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `COUNTRY_NM` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`Country_ID`, `LANG_ID`))
COMMENT = 'Country ID';

-- State ID Table
CREATE TABLE `WMS`.`tblstateid` (
  `COUNTRY_ID` NVARCHAR(10) NOT NULL,
  `STATE_ID` NVARCHAR(10) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `STATE_NM` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`COUNTRY_ID`, `STATE_ID`, `LANG_ID`))
COMMENT = 'State ID';

-- City ID Table
CREATE TABLE `WMS`.`tblcityid` (
  `COUNTRY_ID` NVARCHAR(10) NOT NULL,
  `STATE_ID` NVARCHAR(10) NOT NULL,
  `CITY_ID` NVARCHAR(10) NOT NULL,
  `ZIP_CD` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `CITY_NM` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`COUNTRY_ID`, `STATE_ID`, `CITY_ID`, `ZIP_CD`, `LANG_ID`))
COMMENT = 'City ID';

-- Variant ID Table
CREATE TABLE `WMS`.`tblvariantid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `VAR_ID`NVARCHAR(50) NOT NULL,
  `VAR_TYP` NVARCHAR(20) NOT NULL,
  `VAR_SUB_ID` NVARCHAR(50) NOT NULL,
  `VAR_ID_TEXT` NVARCHAR(50) NULL,
  `VAR_SUB_ID_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL, 
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `VAR_ID`, `VAR_TYP`, `VAR_SUB_ID`))
COMMENT = 'Variant ID';

-- Item type ID Table
CREATE TABLE `WMS`.`tblitemtypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ITM_TYPE_ID` INTEGER NOT NULL,
  `ITM_TYP` NVARCHAR(200) NOT NULL,
  `IS_DELETED` INT NULL,   
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `ITM_TYPE_ID`, `ITM_TYP`))
COMMENT = 'Item type ID';

-- Item Group ID Table
CREATE TABLE `WMS`.`tblitemgroupid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ITM_TYPE_ID` INTEGER NOT NULL,
  `ITM_GRP_ID` INTEGER NOT NULL,
  `IMT_GRP` NVARCHAR(200) NOT NULL,
  `IS_DELETED` INT NULL,     
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `ITM_TYPE_ID`, `ITM_GRP_ID`, `IMT_GRP`))
COMMENT = 'Item Group ID';

-- Sub Item Group ID Table
CREATE TABLE `WMS`.`tblsubitemgroupid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ITM_TYP_ID` INTEGER NOT NULL,
  `ITM_GRP_ID` INTEGER NOT NULL,
  `SUB_ITM_GRP_ID` INTEGER NOT NULL,
  `SUB_ITM_GRP` NVARCHAR(200) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `SUB_ITM_GRP_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,    
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `ITM_TYP_ID`, `ITM_GRP_ID`, `SUB_ITM_GRP_ID`, `SUB_ITM_GRP`, `LANG_ID`))
COMMENT = 'Sub Item Group ID';

-- Status ID Table
CREATE TABLE `WMS`.`tblstatusid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `STATUS_ID` INTEGER NOT NULL,
  `STATUS_TEXT` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,    
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`LANG_ID`,`C_ID`,`PLANT_ID`,`WH_ID`,`STATUS_ID`))
COMMENT = 'Status ID';

-- Refdoctype ID Table
CREATE TABLE `WMS`.`tblrefdoctypeid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `REFDOCYTYPE_ID` INTEGER NOT NULL,
  `REFDOC_TEXT` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,    
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`,`PLANT_ID`, `WH_ID`,`REFDOCYTYPE_ID`))
COMMENT = 'Refdoctype ID';

-- Control Process ID Table
CREATE TABLE `WMS`.`tblcontrolprocessid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `CTRL_PROCESS_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `CTRL_PROCESS` NVARCHAR(50) NULL,
  `IS_DELETED` INT NULL,    
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`,`PLANT_ID`,`WH_ID`,`CTRL_PROCESS_ID`,`LANG_ID`))
COMMENT = 'Control Process ID';

-- Sublevel ID Table
CREATE TABLE `WMS`.`tblsublevelid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `LEVEL_ID` INTEGER NOT NULL,
  `SUB_LEVEL_ID` INTEGER NOT NULL, 
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `SUB_LEVEL` NVARCHAR(50) NOT NULL,   
  `IS_DELETED` INT NULL,    
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`,`PLANT_ID`,`WH_ID`,`LEVEL_ID`,`SUB_LEVEL_ID`,`LANG_ID`,`SUB_LEVEL`))
COMMENT = 'sublevel ID';

-- Process Sequence ID Table
CREATE TABLE `WMS`.`tblprocesssequenceid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `PROCESS_ID` INTEGER NOT NULL,
  `SUB_PROCESS_SEQ_ID` INTEGER NOT NULL, 
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `PROCESS` NVARCHAR(50) NOT NULL,
  `SUBPROCESS` NVARCHAR(50) NOT NULL,   
  `IS_DELETED` INT NULL,    
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`,`PLANT_ID`,`WH_ID`,`PROCESS_ID`,`SUB_PROCESS_SEQ_ID`,`LANG_ID`,`PROCESS`,`SUBPROCESS`))
COMMENT = 'processsequence ID';

----NUMBER RANGE--TABLE
CREATE TABLE `WMS`.`tblnumberrangeid` (
	`LANG_ID` NVARCHAR(5) NOT NULL, 
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`NUM_RAN_CODE` INTEGER NOT NULL,
	`FISCAL_YEAR` INTEGER NOT NULL,    
	`NUM_RAN_OBJ` NVARCHAR(500) NOT NULL,
	`NUM_RAN_FROM` INTEGER NULL,  
	`NUM_RAN_TO` INTEGER NULL,
	`NUM_RAN_CURRENT` NVARCHAR(200) NULL,	
	`IS_DELETED` INT NULL,    
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,
  PRIMARY KEY (`LANG_ID`,`C_ID`,`PLANT_ID`,`WH_ID`,`NUM_RAN_CODE`,`FISCAL_YEAR`))
COMMENT = 'tblnumberrange';

------ Bin Class ID Table
CREATE TABLE `WMS`.`tblbinclassid` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `BIN_CL_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,  
  `BIN_CLASS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`C_ID`, `PLANT_ID`, `WH_ID`, `BIN_CL_ID`, `LANG_ID`))
COMMENT = 'Bin Class ID';

-- Master Scripts

USE WMS;

-- ROLE ACCESS Table
CREATE TABLE `WMS`.`tblroleaccess` (
	
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`USR_ROLE_ID` INTEGER NOT NULL,
	`MENU_ID` INTEGER NOT NULL,
	`SUB_MENU_ID` INTEGER NOT NULL,
	`AUT_OBJ_ID` INTEGER NULL,
	`AUT_OBJ_VALUE` NVARCHAR(50) NULL,
	`USR_ROLE_NM` NVARCHAR(200) NULL,
	`USR_ROLE_TEXT` NVARCHAR(500) NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CREATE` BOOLEAN NULL,
	`EDIT` BOOLEAN NULL,
	`VIEW` BOOLEAN NULL,
	`DELETE` BOOLEAN NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,	

  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `USR_ROLE_ID`, `MENU_ID`, `SUB_MENU_ID`))
COMMENT = 'ROLE ACCESS';

	
-- USER MANAGEMENT Table
CREATE TABLE `WMS`.`tblusermanagement` (
	
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`USR_ID` NVARCHAR(50) NOT NULL,
	`USR_ROLE_ID` INTEGER NOT NULL,
	`USR_TYP_ID` INTEGER NULL,
	`PASSWORD` NVARCHAR(500) NULL,
	`USER_NM` NVARCHAR(50) NULL,
	`FST_NM` NVARCHAR(50) NULL,
	`LST_NM` NVARCHAR(50) NULL,
	`STATUS_ID` INTEGER NULL,
	`DATE_FOR_ID` INTEGER NULL,
	`CUR_DECIMAL` INTEGER NULL,
	`DEC_NOT_ID` INTEGER NULL,
	`TIME_ZONE` NVARCHAR(50) NULL,
	`MAIL_ID` NVARCHAR(500) NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,
	
  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `USR_ID`, `USR_ROLE_ID`))
COMMENT = 'USER MANAGEMENT';


-- HHT USER Table
CREATE TABLE `WMS`.`tblhhtuser` (

	`LANG_ID` NVARCHAR(5) NULL,
	`C_ID` NVARCHAR(50) NULL,
	`PLANT_ID` NVARCHAR(50) NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`USR_ID` NVARCHAR(50) NOT NULL,
	`PASSWORD` NVARCHAR(50) NULL,
	`USER_NM` NVARCHAR(50) NULL,
	`STATUS_ID` INTEGER NULL,
	`CASE_RECEIPT` BOOLEAN NULL,
	`ITEM_RECEIPT` BOOLEAN NULL,
	`PUTAWAY` BOOLEAN NULL,
	`TRANSFER` BOOLEAN NULL,
	`PICKING` BOOLEAN NULL,
	`QUALITY` BOOLEAN NULL,
	`INVENTORY` BOOLEAN NULL,
	`CUSTOMER_RET` BOOLEAN NULL,
	`SUPPLIER_RET` BOOLEAN NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

  PRIMARY KEY ( `WH_ID`, `USR_ID`))
COMMENT = 'HHT USER';

------------------------------------------------------------------------------------------
ALTER TABLE `WMS`.`tblusermanagement` 
CHANGE COLUMN `c_id` `c_id` VARCHAR(255) NOT NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(255) NOT NULL ,
CHANGE COLUMN `plant_id` `plant_id` VARCHAR(255) NOT NULL ,
CHANGE COLUMN `usr_role_id` `usr_role_id` BIGINT NOT NULL ,
CHANGE COLUMN `wh_id` `wh_id` VARCHAR(255) NOT NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`usr_id`, `lang_id`, `c_id`, `plant_id`, `wh_id`, `usr_role_id`)