-- Master Scripts

USE WMS;

-- IM BASIC DATA Table
CREATE TABLE `WMS`.`tblImBasicDataID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ITM_CODE` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `UOM_ID` NVARCHAR(10) NOT NULL,
  `TEXT` NVARCHAR(500) NULL,
  `Model` NVARCHAR(50) NULL,
  `SPEC_01` NVARCHAR(200) NULL,
  `SPEC_02` NVARCHAR(200) NULL,
  `EAN_UPC_NO` NVARCHAR(200) NULL,
  `MFR_PART` NVARCHAR(200) NULL,
  `ITM_TYP_ID` INTEGER NULL,
  `ITM_GRP_ID` INTEGER NULL,
  `SUB_ITM_GRP_ID` INTEGER NULL,
  `ST_SEC_ID` INTEGER NULL,
  `TOT_STK` DECIMAL(30,4) NULL,
  `MIN_STK` DECIMAL(30,4) NULL,
  `RE_ORD_LVL` DECIMAL(30,4) NULL,
  `REP_QTY` DECIMAL(30,4) NULL,
  `SAFTY_STCK` DECIMAL(30,4) NULL,
  `ITM_BARCODE` NVARCHAR(50) NULL,
  `LENGTH` DECIMAL(30,4) NULL,
  `WITDH` DECIMAL(30,4) NULL,
  `HEIGHT` DECIMAL(30,4) NULL,
  `DIM_UOM` NVARCHAR(50) NULL,
  `VOLUME` DECIMAL(30,4) NULL,
  `VOL_UOM` NVARCHAR(50) NULL,
  `QPC_01` DECIMAL(30,4) NULL,
  `QPC_02` DECIMAL(30,4) NULL,
  `UNIT_PR` DECIMAL(30,2) NULL,
  `CURR_ID` INTEGER NULL,
  `GR_WT` DECIMAL(30,4) NULL,
  `NT_WT` DECIMAL(30,4) NULL,
  `WT_UOM` NVARCHAR(50) NULL,
  `PREF_ST_BIN` NVARCHAR(50) NULL,
  `IMAGE` MEDIUMBLOB NULL,
  `IT_CL` NVARCHAR(50) NULL,
  `CROSS_DK_IND` BOOLEAN NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `ITM_CODE`, `LANG_ID`, `UOM_ID`))
COMMENT = 'IM BASIC DATA';


-- IM STRATEGIES Table
CREATE TABLE `WMS`.`tblImStrategiesID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ITM_CODE` NVARCHAR(50) NOT NULL,
  `STR_TYP_ID` NVARCHAR(50) NOT NULL,
  `SEQ_IND` INTEGER NOT NULL,  
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CAP_CHK` BOOLEAN NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `ITM_CODE`, `STR_TYP_ID`, `SEQ_IND`, `LANG_ID`))
COMMENT = 'IM STRATEGIES';


-- IM ALTERNATE UOM Table
CREATE TABLE `WMS`.`tblImAlternateUomID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ITM_CODE` NVARCHAR(50) NOT NULL,	
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `UOM_ID` NVARCHAR(10) NOT NULL,
  `ALT_UOM` NVARCHAR(50) NOT NULL,
  `S_NO` INTEGER NULL,  
  `FRM_UNT` INTEGER NULL,  
  `TO_UNT` INTEGER NULL,  
  `QPC_01` DECIMAL(30,4) NULL,
  `QPC_02` DECIMAL(30,4) NULL,
  `ALT_UOM_BAR` NVARCHAR(50) NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `ITM_CODE`, `LANG_ID`, `UOM_ID`, `ALT_UOM`))
COMMENT = 'IM ALTERNATE UOM';


-- IM BATCH SERIAL Table
CREATE TABLE `WMS`.`tblImBatchSerialID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ITM_CODE` NVARCHAR(50) NOT NULL,	
  `ST_MTD` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `MAINT` NVARCHAR(50) NULL,
  `RGE_FRM` NVARCHAR(200) NULL,
  `RGE_TO` NVARCHAR(200) NULL,
  `CUR_NO` NVARCHAR(200) NULL,
  `SHL_LIF_IND` BOOLEAN NULL,
  `TOT_SHL_LIF` DECIMAL(30,4) NULL,
  `SHL_LIF_PERIOD` NVARCHAR(10) NULL,
  `SHL_LIF_NOT` DECIMAL(30,4) NULL,
  `SHL_LIF_NOT_PERIOD` NVARCHAR(10) NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `ITM_CODE`, `ST_MTD`, `LANG_ID`))
COMMENT = 'IM BATCH SERIAL';


-- IM VARIANT Table
CREATE TABLE `WMS`.`tblImVariantID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ITM_CODE` NVARCHAR(50) NOT NULL,	
  `VAR_ID` INTEGER NOT NULL,
  `VAR_TYP` NVARCHAR(20) NOT NULL,	
  `VAR_SUB_ID` NVARCHAR(50) NOT NULL,	
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `VAR_IND` BOOLEAN NULL,
  `SPEC_FROM` NVARCHAR(50) NULL,
  `SPEC_TO` NVARCHAR(50) NULL,
  `SPEC_UOM` NVARCHAR(50) NULL,
  `VAR_BAR_CODE` NVARCHAR(50) NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `ITM_CODE`,  `VAR_ID`, `VAR_TYP`,  `VAR_SUB_ID`, `LANG_ID`))
COMMENT = 'IM VARIANT';


-- IM PALLETIZATION Table
CREATE TABLE `WMS`.`tblImPalletizationID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ITM_CODE` NVARCHAR(50) NOT NULL,	
  `PAL_LVL` NVARCHAR(10) NOT NULL,	
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `PAL_IND` BOOLEAN NULL,
  `PAL_LEN` DECIMAL(30,4) NULL,
  `PAL_WID` DECIMAL(30,4) NULL,
  `PAL_HGT` DECIMAL(30,4) NULL,
  `PAL_DIM_UOM` NVARCHAR(50) NULL,
  `ITM_PAL_QTY` DECIMAL(30,4) NULL,
  `CASE_LEN` DECIMAL(30,4) NULL,
  `CASE_WID` DECIMAL(30,4) NULL,
  `CASE_HGT` DECIMAL(30,4) NULL,
  `CASE_DIM_UOM` NVARCHAR(50) NULL,
  `ITM_CASE_QTY` DECIMAL(30,4) NULL,
  `CASE_PAL_QTY` DECIMAL(30,4) NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `ITM_CODE`,  `PAL_LVL`, `LANG_ID`))
COMMENT = 'IM PALLETIZATION';


-- IM PARTNER Table
CREATE TABLE `WMS`.`tblImVariantID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ITM_CODE` NVARCHAR(50) NOT NULL,	
  `PARTNER_TYP` NVARCHAR(50) NOT NULL,	
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `PARTNER_CODE` NVARCHAR(50) NOT NULL,  
  `PARTNER_ITM_CODE` NVARCHAR(200) NULL,
  `PARTNER_ITM_BAR` NVARCHAR(50) NULL,
  `MFR_BAR` NVARCHAR(200) NULL,
  `BRND_NM` NVARCHAR(200) NULL,
  `STK` DECIMAL(30,4) NULL,
  `STK_UOM` NVARCHAR(50) NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `ITM_CODE`, `PARTNER_TYP`, `LANG_ID`, `PARTNER_CODE`))
COMMENT = 'IM PARTNER';


-- IM PACKING Table
CREATE TABLE `WMS`.`tblImPackingID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ITM_CODE` NVARCHAR(50) NOT NULL,	
  `PACK_MAT_NO` NVARCHAR(50) NOT NULL,	
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `PACK_IND` BOOLEAN NULL,
  `PACK_MAT_TEXT` NVARCHAR(500) NULL,
  `PACK_QTY` DECIMAL(30,4) NULL,
  `REQ_SHRNK` BOOLEAN NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `ITM_CODE`,  `PACK_MAT_NO`, `LANG_ID`))
COMMENT = 'IM PACKING';


-- STORAGE BIN Table
CREATE TABLE `WMS`.`tblStorageBinID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `FL_ID` INTEGER NOT NULL,
  `ST_SEC_ID` INTEGER NOT NULL,
  `ROW_ID` NVARCHAR(10) NOT NULL,
  `AISLE_ID` NVARCHAR(10) NOT NULL,
  `SPAN_ID` NVARCHAR(10) NOT NULL,
  `SHELF_ID` NVARCHAR(10) NOT NULL,
  `ST_BIN` NVARCHAR(50) NOT NULL
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `BIN_SECTION_ID` INTEGER NOT NULL,
  `ST_TYP_ID` INTEGER NOT NULL,
  `BIN_CL_ID` INTEGER NOT NULL,
  `ST_BIN_TEXT` NVARCHAR(500) NULL,
  `BIN_BAR` NVARCHAR(50) NULL,
  `ST_CL_ID` INTEGER NULL,
  `ST_BIN_TYP_ID` INTEGER NULL,
  `CTRL_TYP_ID` INTEGER NULL,
  `BLK_REASON` NVARCHAR(500) NULL,
  `LENGTH` DECIMAL(30,4) NULL,
  `WIDTH` DECIMAL(30,4) NULL,
  `HEIGHT` DECIMAL(30,4) NULL,
  `DIM_UOM` NVARCHAR(50) NULL,
  `TOT_WT` DECIMAL(30,4) NULL,
  `WT_UOM` NVARCHAR(50) NULL,
  `OCC_WT` DECIMAL(30,4) NULL,
  `REM_WT` DECIMAL(30,4) NULL,
  `TOT_VOL` DECIMAL(30,4) NULL,
  `VOL_UOM` NVARCHAR(50) NULL,
  `OCC_VOL` DECIMAL(30,4) NULL,
  `REM_VOL` DECIMAL(30,4) NULL,
  `ST_TEMP_FROM` DECIMAL(30,4) NULL,
  `ST_TEMP_TO` DECIMAL(30,4) NULL,
  `ST_TEMP_CUR` DECIMAL(30,4) NULL,
  `TEMP_UOM` NVARCHAR(10) NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
 
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `FL_ID`, `ST_SEC_ID`, `ROW_ID`, `AISLE_ID`, `SPAN_ID`, `SHELF_ID`, `ST_BIN`, `LANG_ID`,  `BIN_SECTION_ID`, `ST_TYP_ID`, `BIN_CL_ID` ))
COMMENT = 'STORAGE BIN';



-- HANDLING EQUIPMENT Table
CREATE TABLE `WMS`.`tblHandlingEquipmentID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `HE_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CATEGORY` NVARCHAR(50) NULL,	
  `HU_UNIT` NVARCHAR(50) NULL,	
  `AQU_DT` DATE NULL,	
  `AQU_VAL` DECIMAL(30,4) NULL,
  `CURR_ID` INTEGER NULL,
  `MOD_NO` NVARCHAR(200) NULL,
  `MFR_PART` NVARCHAR(200) NULL,
  `CTY_ORG` NVARCHAR(50) NULL,	
  `HE_BAR` NVARCHAR(50) NULL,	
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `HE_ID`,  `LANG_ID`))
COMMENT = 'HANDLING EQUIPMENT';



-- HANDLING UNIT Table
CREATE TABLE `WMS`.`tblHandlingUnitID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `HU_UNIT` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `LENGTH` DECIMAL(30,4) NULL,
  `LEN_UOM` NVARCHAR(50) NULL,
  `WIDTH` DECIMAL(30,4) NULL,
  `WID_UOM` NVARCHAR(50) NULL,
  `HGT` DECIMAL(30,4) NULL,
  `HGT_UOM` NVARCHAR(50) NULL,
  `VOLUME` DECIMAL(30,4) NULL,
  `VOL_UOM` NVARCHAR(50) NULL,
  `Weight` DECIMAL(30,4) NULL,
  `WT_UOM` NVARCHAR(50) NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `HU_UNIT`, `LANG_ID`))
COMMENT = 'HANDLING UNIT';



-- BOM Table
CREATE TABLE `WMS`.`tblBomID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `PAR_ITM_CODE` NVARCHAR(50) NOT NULL,
  `CHL_ITEM_CODE` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `PAR_ITM_QTY` DECIMAL(30,4) NULL,
  `CHL_ITM_QTY` DECIMAL(30,4) NULL,
  `STATUS` BOOLEAN NULL,    
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `PAR_ITM_CODE`, `CHL_ITEM_CODE`, `LANG_ID`))
COMMENT = 'BOM';



-- BUSINESS PARTNER Table
CREATE TABLE `WMS`.`tblBusinessPartnerID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `PARTNER_TYP` INTEGER NOT NULL,
  `PARTNER_CODE` NVARCHAR(50) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `PARTNER_NM` NVARCHAR(50) NULL,
  `ADD_1` NVARCHAR(5000) NULL,
  `ADD_2` NVARCHAR(5000) NULL,
  `Zone` NVARCHAR(500) NULL,
  `COUNTRY` NVARCHAR(50) NULL,
  `STATE` NVARCHAR(50) NULL,
  `PH_NO` NVARCHAR(500) NULL,
  `FX_NO` NVARCHAR(500) NULL,
  `MAIL_ID` NVARCHAR(500) NULL,
  `REF_TXT` NVARCHAR(500) NULL,
  `LOCATION` NVARCHAR(500) NULL,  
  `LATITUDE` DECIMAL(30,15) NULL,
  `LONGITUDE` DECIMAL(30,15) NULL,
  `ST_TYP_ID` INTEGER NULL,
  `ST_BIN` NVARCHAR(50) NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `PARTNER_TYP`, `PARTNER_CODE`, `LANG_ID`))
COMMENT = 'BUSINESS PARTNER';



-- DOCK Table
CREATE TABLE `WMS`.`tblDockID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `DK_TYPE` NVARCHAR(50) NOT NULL,
  `DK_ID` NVARCHAR(10) NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `DK_CAP` NVARCHAR(50) NULL,
  `DK_TEXT` NVARCHAR(500) NULL,    
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `DK_TYPE`, `DK_ID`, `LANG_ID`))
COMMENT = 'DOCK';




-- WORK CENTER Table
CREATE TABLE `WMS`.`tblWorkCenterID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `WRK_CTR_TYP` NVARCHAR(50) NOT NULL,
  `WRK_CTR_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `WRK_CTR_TYP`, `WRK_CTR_ID`, `LANG_ID`))
COMMENT = 'WORK CENTER';



-- CYCLE COUNT SCHEDULER Table
CREATE TABLE `WMS`.`tblCycleCountSchedulerID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `LEVEL_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `LEVEL_REF` NVARCHAR(50) NULL,
  `CNT_FREQ` NVARCHAR(50) NULL,
  `COUNT_DAY` NVARCHAR(50) NULL,
  `CC_MTD` NVARCHAR(30) NOT NULL,
  `SCHE_NO` NVARCHAR(20) NOT NULL,
  `SUB_LVL_REF` NVARCHAR(50) NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`,`LEVEL_ID`, `LANG_ID`, `CC_MTD`, `SCHE_NO`))
COMMENT = 'CYCLE COUNT SCHEDULER';



-- PACKING MATERIAL Table
CREATE TABLE `WMS`.`tblPackingMaterialID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `PACK_MAT_NO` NVARCHAR(50) NOT NULL,
  `PACK_MAT_TEXT` NVARCHAR(500) NULL,
  `LENGTH` DECIMAL(30,4) NULL,
  `WIDTH` DECIMAL(30,4) NULL,
  `HEIGHT` DECIMAL(30,4) NULL,
  `DIM_UOM` NVARCHAR(50) NULL,
  `VOLUME` DECIMAL(30,4) NULL,
  `VOL_UOM` NVARCHAR(50) NULL,
  `PARTNER_CODE` NVARCHAR(50) NULL,
  `TOT_STOCK` DECIMAL(30,4) NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `PACK_MAT_NO`))
COMMENT = 'PACKING MATERIAL';



-- NUMBER RANGE ITEM Table
CREATE TABLE `WMS`.`tblNumberRangeItemID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ITM_TYP_ID` INTEGER NOT NULL,
  `SEQ_NO` INTEGER NOT NULL,
  `NUM_RAN_TYPE` NVARCHAR(50) NULL,
  `NUM_RAN_FROM` NVARCHAR(50) NULL,
  `NUM_RAN_TO` NVARCHAR(50) NULL,
  `NUM_RAN_CURRENT` NVARCHAR(50) NULL,
  `ISDELETED` INTEGER NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`,`ITM_TYP_ID`, `SEQ_NO`))
COMMENT = 'NUMBER RANGE ITEM';



-- NUMBER RANGE STORAGE BIN Table
CREATE TABLE `WMS`.`tblNumberRangeStorageBinID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `FL_ID` INTEGER NOT NULL,
  `ST_SEC_ID` INTEGER NOT NULL,
  `ROW_ID` NVARCHAR(10) NOT NULL,
  `AISLE_ID` NVARCHAR(10) NOT NULL,
  `SPAN_ID` NVARCHAR(10) NOT NULL,
  `SHELF_ID` NVARCHAR(10) NOT NULL,
  `NUM_RAN_TYPE` NVARCHAR(50) NULL,
  `NUM_RAN_FROM` NVARCHAR(50) NULL,
  `NUM_RAN_TO` NVARCHAR(50) NULL,
  `NUM_RAN_CURRENT` NVARCHAR(50) NULL,  
  `ISDELETED` INTEGER NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`,`FL_ID`, `ST_SEC_ID`, `ROW_ID`, `AISLE_ID`, `SPAN_ID`, `SHELF_ID`))
COMMENT = 'NUMBER RANGE STORAGE BIN';



-- AUDIT LOG Table
CREATE TABLE `WMS`.`tblAuditLogID` (
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `AUD_FILE_NO` NVARCHAR(20) NOT NULL,
  `FISCAL YEAR` INTEGER NOT NULL,
  `OBJ_NM` NVARCHAR(50) NULL,
  `SCREEN_NO` NVARCHAR(10) NOT NULL,
  `SUB_SCREEN_NO` NVARCHAR(10) NOT NULL,
  `TABLE_NM` NVARCHAR(50) NULL,
  `MOD_FIELD` NVARCHAR(50) NULL,
  `OLD_VL` NVARCHAR(50) NULL,
  `NEW_VL` NVARCHAR(50) NULL,  
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`,`AUD_FILE_NO`, `FISCAL YEAR`))
COMMENT = 'AUDIT LOG';