-- Master Scripts

USE WMS;

-- INHOUSE TRANSFER HEADER Table
CREATE TABLE `WMS`.`tblinhousetransferheader` (
  
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`TR_NO` NVARCHAR(20) NOT NULL,
	`TR_TYP_ID` INTEGER NOT NULL,
	`TR_MTD` NVARCHAR(20) NULL,
	`STATUS_ID` INTEGER NULL,
	`REMARK` NVARCHAR(500) NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`IT_CTD_BY` NVARCHAR(50) NULL,
	`IT_CTD_ON` DATETIME NULL,
	`IT_UTD_BY` NVARCHAR(50) NULL,
	`IT_UTD_ON` DATETIME NULL,

  PRIMARY KEY (`LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `TR_NO`, `TR_TYP_ID`))
COMMENT = 'INHOUSE TRANSFER HEADER';


-- INHOUSE TRANSFER LINE Table
CREATE TABLE `WMS`.`tblinhousetransferline` (
	
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`TR_NO` NVARCHAR(20) NOT NULL,
	`SRCE_ITM_CODE` NVARCHAR(50) NOT NULL,
	`SRCE_STCK_TYP_ID` INTEGER NULL,
	`SRCE_ST_BIN` NVARCHAR(50) NULL,
	`TGT_ITM_CODE` NVARCHAR(50) NULL,
	`TGT_STCK_TYP_ID` INTEGER NULL,
	`TGT_ST_BIN` NVARCHAR(50) NULL,
	`TR_ORD_QTY` DECIMAL(30,4) NULL,
	`TR_CNF_QTY` DECIMAL(30,4) NULL,
	`AVL_QTY` DECIMAL(30,4) NULL,
	`TR_UOM` NVARCHAR(50) NULL,
	`PAL_CODE` NVARCHAR(50) NULL,
	`CASE_CODE` NVARCHAR(50) NULL,
	`PACK_BARCODE` NVARCHAR(50) NULL,
	`SP_ST_IND_ID` INTEGER NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`REMARK` NVARCHAR(500) NULL,
	`IT_CTD_BY` NVARCHAR(50) NULL,
	`IT_CTD_ON` DATETIME NULL,
	`IT_CNF_BY` NVARCHAR(50) NULL,
	`IT_CNF_ON` DATETIME NULL,
	`IT_UTD_BY` NVARCHAR(50) NULL,
	`IT_UTD_ON` DATETIME NULL,
  
  PRIMARY KEY (`LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `TR_NO`, `SRCE_ITM_CODE`))
COMMENT = 'INHOUSE TRANSFER LINE';

