-- Accounting Setup DB Scripts
-- Database
USE MNRCLARA;

-- QUOTATION HEADER Table
CREATE TABLE `MNRCLARA`.`tblquotationheader` (
	`QUOTE_NO` NVARCHAR(20) NOT NULL,
	`QUOTE_REV_NO` INTEGER NOT NULL,	
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`CLASS_ID` INTEGER NOT NULL,	
	`MATTER_NO` NVARCHAR(20) NOT NULL,
	`CLIENT_ID` NVARCHAR(20) NOT NULL,
	`CASE_CATEGORY_ID` INTEGER NULL, -- 
	`CASE_SUB_CATEGORY_ID` INTEGER NULL, --
	`QUOTE_DATE` DATETIME NULL, -- 
	`QUOTE_AMT` DECIMAL(20,2) NOT NULL,	
	`FIRST_LAST_NM` NVARCHAR(200) NULL,
	`CORPORATION` NVARCHAR(200) NULL,	
	`CURRENCY` NVARCHAR(5) NULL,
	`DUE_DATE` DATETIME NULL,
	`PAYMENT_PLAN_NO` NVARCHAR(20) NULL,
	`TERM_TEXT` NVARCHAR(200) NULL,
	`SENT_ON` DATETIME NULL,
	`APPROVED_ON` DATETIME NULL,
	`STATUS_ID` INTEGER NULL,
	`IS_DELETED` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,
	
	PRIMARY KEY (`QUOTE_NO`, `QUOTE_REV_NO`))
COMMENT = 'QUOTATION HEADER';

-- QUOTATION LINE Table
CREATE TABLE `MNRCLARA`.`tblquotationline` (
	`QUOTE_NO` NVARCHAR(20) NOT NULL,
	`QUTO_REV_NO` INTEGER NOT NULL,
	`SERIAL_NO` INTEGER NOT NULL,
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`CLASS_ID` INTEGER NOT NULL,
	`MATTER_NO` NVARCHAR(20) NOT NULL,
	`CLIENT_ID` NVARCHAR(20) NOT NULL,	
	`ITEM_NO` INTEGER NOT NULL,
	`ITEM_TEXT` NVARCHAR(500) NULL,
	`TK_CODE` NVARCHAR(10) NULL,
	`RATE_HR` DECIMAL(20,2) NULL,
	`QUANTITY` DECIMAL(20,2) NULL,
	`TOTAL_AMT` DECIMAL(20,2) NOT NULL,
	`CURRENCY` NVARCHAR(5) NULL,
	`STATUS_ID` INTEGER NULL,
	`IS_DELETED` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

	PRIMARY KEY ( `SERIAL_NO`, `QUOTE_NO`, `QUTO_REV_NO`))
COMMENT = 'QUOTATION LINE';

-- PAYMENT PLAN HEADER Table
CREATE TABLE `MNRCLARA`.`tblpaymentplanheader` (	
	`PAYMENT_PLAN_NO` NVARCHAR(20) NOT NULL,
	`PLAN_REV_NO` INTEGER NOT NULL,	
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`CLASS_ID` INTEGER NOT NULL,
	`CLIENT_ID` NVARCHAR(20) NOT NULL,
	`PAYMENT_PLAN_DATE` DATETIME NULL, --
	`MATTER_NO` NVARCHAR(20) NULL,	
	`QUOTE_NO` NVARCHAR(20) NULL,
	`START_DATE` DATETIME NULL, -- 
	`END_DATE` DATETIME NULL,
	`NO_OF_INSTAL` INTEGER NULL, --
	`PAYMENT_PLAN_AMT` DECIMAL(20,2) NULL, --
	`DUE_AMOUNT` DECIMAL(20,2) NULL, --
	`INSTALL_AMT` DECIMAL(20,2) NULL,
	`CURRENCY` NVARCHAR(5) NULL,
	`PAYMENT_CAL_DAY` INTEGER NULL, --
	`PAY_PLAN_TEXT` NVARCHAR(500) NULL,
	`SENT_ON` DATETIME NULL,
	`APPROVED_ON` DATETIME NULL,
	`STATUS_ID` INTEGER NOT NULL,
	`IS_DELETED` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,
	
	PRIMARY KEY (`PAYMENT_PLAN_NO`, `PLAN_REV_NO`))
COMMENT = 'PAYMENT PLAN HEADER';

-- PAYMENT PLAN LINE Table
CREATE TABLE `MNRCLARA`.`tblpaymentplanline` (
	`PAYMENT_PLAN_NO` NVARCHAR(20) NOT NULL,
	`PLAN_REV_NO` INTEGER NOT NULL,
	`ITEM_NO` INTEGER NOT NULL,	
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`CLASS_ID` INTEGER NOT NULL,
	`CLIENT_ID` NVARCHAR(20) NOT NULL,
	`DUE_DATE` DATETIME NULL, --
	`DUE_AMOUNT` DECIMAL(20,2) NULL, --
	`REMAIN_DUE_NOW` DECIMAL(20,2) NULL, --
	`MATTER_NO` NVARCHAR(20) NULL,
	`QUOTE_NO` NVARCHAR(20) NULL,
	`CURRENCY` NVARCHAR(5) NULL,
	`REMINDER_DAYS` INTEGER NULL,
	`REMINDER_DATE` DATETIME NULL,
	`REMINDER_STATUS` NVARCHAR(50) NULL,
	`STATUS_ID` INTEGER NULL,
	`IS_DELETED` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

	PRIMARY KEY (`PAYMENT_PLAN_NO`, `PLAN_REV_NO`, `ITEM_NO`))
COMMENT = 'PAYMENT PLAN LINE';

-- INVOICE HEADER Table
CREATE TABLE `MNRCLARA`.`tblinvoiceheader` (
	
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`CLASS_ID` INTEGER NOT NULL,
	`MATTER_NO` NVARCHAR(20) NOT NULL,
	`CLIENT_ID` NVARCHAR(20) NOT NULL,
	
	`PRE_BILL_BATCH_NO` NVARCHAR(20) NOT NULL,
	`PRE_BILL_NO` NVARCHAR(20) NOT NULL,
	`PRE_BILL_DATE` DATETIME NOT NULL,
	
	`CASE_CATEGORY_ID` INTEGER NULL, --
	`CASE_SUB_CATEGORY_ID` INTEGER NULL, --
	`INVOICE_NO` NVARCHAR(20) NOT NULL,
	`INVOICE_FISCAL_YEAR` NVARCHAR(10) NOT NULL,
	`INVOICE_PERIOD` NVARCHAR(10) NOT NULL,
	`POSTING_DATE` DATETIME NULL, --
	`INVOICE_REFERENCE` NVARCHAR(1000) NULL, --
	`INVOICE_DATE` DATETIME NULL,
	`PARTNER_ASSIGNED` NVARCHAR(50) NOT NULL,
	`BILL_HOURS` DECIMAL(20,2) NULL,
	`INVOICE_AMT` DECIMAL(20,2) NULL,
	`CURRENCY` NVARCHAR(5) NULL,
	`AR_ACCOUNT_NO` NVARCHAR(20) NULL,
	`PAYMENT_PLAN_NO` NVARCHAR(20) NULL,
	`START_DATE` DATETIME NULL,
	`COST_CUT_DATE` DATETIME NULL,
	`PAYMENT_CUT_DATE` DATETIME NULL,
	`TRUST_CUT_DATE` DATETIME NULL,
	`PAID_AMOUNT` DECIMAL(20,2) NULL,
	`REMAIN_BAL` DECIMAL(20,2) NULL,
	`STATUS_ID` INTEGER NULL,
	`IS_DELETED` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`CTD_BY` NVARCHAR(50) NULL,	
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

	PRIMARY KEY (`LANG_ID`, `CLASS_ID`, `MATTER_NO`, `CLIENT_ID`, `INVOICE_NO`, `INVOICE_FISCAL_YEAR`, `INVOICE_PERIOD`))
COMMENT = 'INVOICE HEADER';

-- INVOICE LINE Table
CREATE TABLE `MNRCLARA`.`tblinvoiceline` (
	
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`CLASS_ID` INTEGER NOT NULL,
	`MATTER_NO` NVARCHAR(20) NOT NULL,
	`CLIENT_ID` NVARCHAR(20) NOT NULL,
	`INVOICE_NO` NVARCHAR(20) NOT NULL,
	`SERIAL_NO` INTEGER NOT NULL,
	`INVOICE_FISCAL_YEAR` NVARCHAR(10) NOT NULL,
	`INVOICE_PERIOD` NVARCHAR(10) NOT NULL,
	`ITEM_NO` INTEGER NOT NULL,
	`ACTIVITY_CODE` NVARCHAR(20) NULL,
	`INVOICE_TEXT` NVARCHAR(1000) NULL,
	`TASK_CODE` NVARCHAR(20) NULL,
	`TIME_TICKET_DATE` DATETIME NULL,
	`TK_CODE` NVARCHAR(10) NULL,
	`BILL_TYPE` NVARCHAR(20) NULL,
	`BILL_TIME` DECIMAL(20,2) NULL,
	`BILL_AMOUNT` DECIMAL(20,2) NULL,
	`CURRENCY` NVARCHAR(5) NULL,
	`GL_ACCOUNT` NVARCHAR(10) NULL,
	`STATUS_ID` INTEGER NULL,
	`IS_DELETED` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

	PRIMARY KEY (`LANG_ID`, `CLASS_ID`, `MATTER_NO`, `CLIENT_ID`, `INVOICE_NO`, `ITEM_NO`))
COMMENT = 'INVOICE LINE';

--PAYMENT UPDATE Table
CREATE TABLE `MNRCLARA`.`tblpaymentupdate` (
	
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`CLASS_ID` INTEGER NOT NULL,
	`MATTER_NO` NVARCHAR(20) NOT NULL,
	`CLIENT_ID` NVARCHAR(20) NOT NULL,
	`PAYMENT_NO` NVARCHAR(20) NOT NULL,
	`PAYMENT_FISCAL_YEAR` NVARCHAR(10) NOT NULL,
	`PAYMENT_PERIOD` NVARCHAR(10) NOT NULL,
	`POSTING_DATE` DATETIME NOT NULL,
	`INVOCIE_REFERENCE` NVARCHAR(20) NOT NULL,
	`PAYMENT_DATE` DATETIME NULL,
	`PMT_TYPE` NVARCHAR(5) NULL,
	`PAYMENT_AMT` DECIMAL(20,2) NULL,
	`CURRENCY` NVARCHAR(5) NULL,
	`PAYMENT_MODE` NVARCHAR(50) NULL,
	`CASHIER_ID` NVARCHAR(50) NULL,
	`CHECK_ISSUE_BANK` NVARCHAR(50) NULL,
	`CHECK_ACCT_NO` INTEGER NULL,
	`CHECK_ROUTING_NO` INTEGER NULL,
	`CHECK_NO` NVARCHAR(50) NULL,
	`CHECK_ISSUER_NAME` NVARCHAR(50) NULL,
	`CHECK_DATE` DATETIME NULL,
	`CHECK_CLEARING_DATE` DATETIME NULL,
	`CARD_TYPE` NVARCHAR(50) NULL,
	`CARD_NO` INTEGER NULL,
	`NAME_ON_CARD` NVARCHAR(50) NULL,
	`CARD_EXPIRY_DATE` DATETIME NULL,
	`TRANS_NAME` NVARCHAR(50) NULL,
	`TRANS_ACCOUNT_NO` INTEGER NULL,
	`TRANS_ROUTING_NO` INTEGER NULL,
	`TRANS_BANK` NVARCHAR(50) NULL,
	`TRANS_DATE` DATETIME NULL,
	`STATUS_ID` INTEGER NULL,
	`IS_DELETED` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

	PRIMARY KEY (`LANG_ID`, `CLASS_ID`, `MATTER_NO`, `CLIENT_ID`, `PAYMENT_NO`, `PAYMENT_FISCAL_YEAR`, `PAYMENT_PERIOD`, `POSTING_DATE`, `INVOCIE_REFERENCE`))
COMMENT = 'PAYMENT UPDATE';

-- PAYMENT INVOICE LINK Table
CREATE TABLE `MNRCLARA`.`tblpaymentinvoicelink` (
	
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`CLASS_ID` INTEGER NOT NULL,
	`MATTER_NO` NVARCHAR(20) NOT NULL,
	`CLIENT_ID` NVARCHAR(20) NOT NULL,
	`PAYMENT_NO` NVARCHAR(20) NOT NULL,
	`ITEM_NO` INTEGER NOT NULL,
	`PAYMENT_FISCAL_YEAR` NVARCHAR(10) NOT NULL,
	`PAYMENT_PERIOD` NVARCHAR(10) NOT NULL,
	`INVOICE_NO` NVARCHAR(20) NULL,
	`INVOICE_FISCAL_YEAR` NVARCHAR(10) NULL,
	`INVOICE_PERIOD` NVARCHAR(10) NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

	PRIMARY KEY (`LANG_ID`, `CLASS_ID`, `MATTER_NO`, `CLIENT_ID`, `PAYMENT_NO`, `ITEM_NO`, `PAYMENT_FISCAL_YEAR`, `PAYMENT_PERIOD`))
COMMENT = 'PAYMENT INVOICE LINK';

ALTER TABLE `MNRCLARA`.`tblmattertimeticketid` 
CHANGE COLUMN `APP_BILL_TIME` `APP_BILL_TIME` DECIMAL(20,2) NULL DEFAULT NULL ;

-----------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE `tblpaymentupdate` (
  `paymentid` bigint(20) NOT NULL AUTO_INCREMENT,
  `invoice_no` varchar(255) DEFAULT NULL,
  `class_id` bigint(20) DEFAULT NULL,
  `client_id` varchar(255) DEFAULT NULL,
  `ctd_by` varchar(255) DEFAULT NULL,
  `ctd_on` datetime(6) DEFAULT NULL,
  `lang_id` varchar(255) DEFAULT NULL,
  `matter_no` varchar(255) DEFAULT NULL,
  `payment_amount` double DEFAULT NULL,
  `payment_date` datetime(6) DEFAULT NULL,
  `payment_number` varchar(255) DEFAULT NULL,
  `payment_text` varchar(255) DEFAULT NULL,
  `posting_date` datetime(6) DEFAULT NULL,
  `ref_field_1` varchar(255) DEFAULT NULL,
  `ref_field_10` varchar(255) DEFAULT NULL,
  `ref_field_2` varchar(255) DEFAULT NULL,
  `ref_field_3` varchar(255) DEFAULT NULL,
  `ref_field_4` varchar(255) DEFAULT NULL,
  `ref_field_5` varchar(255) DEFAULT NULL,
  `ref_field_6` varchar(255) DEFAULT NULL,
  `ref_field_7` varchar(255) DEFAULT NULL,
  `ref_field_8` varchar(255) DEFAULT NULL,
  `ref_field_9` varchar(255) DEFAULT NULL,
  `status_id` bigint(20) DEFAULT NULL,
  `transaction_type` varchar(255) DEFAULT NULL,
  `payment_code` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`paymentid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

drop table tblquotationheader;
drop table tblquotationline;
drop table tblpaymentplanheader;
drop table tblpaymentplanline;
drop table tblinvoiceheader;
drop table tblinvoiceline;



