-- Client Management DB Scripts

USE MNRCLARA;

-- CLIENTGENERAL Table
CREATE TABLE `MNRCLARA`.`tblclientgeneralid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CLIENT_ID` NVARCHAR(20) NOT NULL,
  `CLIENT_CAT_ID` INTEGER NOT NULL,
  `TRANS_ID` INTEGER NULL,
  `POT_CLIENT_ID` NVARCHAR(20) NULL,
  `INQ_NO` NVARCHAR(20) NULL,
  `IT_FORM_ID` INTEGER NULL,
  `IT_FORM_NO` NVARCHAR(20) NULL,
  `FIRST_NM` NVARCHAR(100) NULL,
  `LAST_NM` NVARCHAR(100) NULL,
  `FIRST_LAST_NM` NVARCHAR(100) NULL,
  `LAST_FIRST_NM` NVARCHAR(100) NULL,
  `CORP_CLIENT_ID` NVARCHAR(20) NULL,
  `REFERRAL_ID` INTEGER NULL,
  `EMAIL_ID` NVARCHAR(100) NULL,
  `CONT_NO` NVARCHAR(30) NULL,
  `ADDRESS_LINE1` NVARCHAR(1000) NULL,
  `ADDRESS_LINE2` NVARCHAR(1000) NULL,
  `ADDRESS_LINE3` NVARCHAR(1000) NULL,
  `CITY` NVARCHAR(100) NULL,
  `STATE` NVARCHAR(100) NULL,
  `COUNTRY` NVARCHAR(30) NULL,
  `ZIP_CODE` NVARCHAR(30) NULL,
  `CONSULT_DATE` NVARCHAR(30) NULL,
  `SSN_ID` NVARCHAR(30) NULL,
  `MAIL_ADDRESS` NVARCHAR(1000) NULL,
  `OCCUPATION` NVARCHAR(100) NULL,
  `STATUS_ID` INTEGER NULL,
  `SUITE_NO` NVARCHAR(30) NULL,
  `WORK` NVARCHAR(30) NULL,
  `HOME` NVARCHAR(30) NULL,
  `FAX` NVARCHAR(30) NULL,
  `ALT_EMAIL_ID` NVARCHAR(100) NULL,
  `IS_MAIL_SAME` BOOLEAN NULL,
  `IS_DELETED` INTEGER NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `CLIENT_ID`))
COMMENT = 'CLIENTGENERAL';


-- CLIENTMATTER Table
CREATE TABLE `MNRCLARA`.`tblclientmatterid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CLIENT_ID` NVARCHAR(20) NOT NULL,
  `MATTER_NO` NVARCHAR(20) NOT NULL,
  `IS_DELETED` INTEGER NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `CLIENT_ID`, `MATTER_NO`))
COMMENT = 'CLIENTMATTER';
  
-- CLIENTEMAIL Table

CREATE TABLE `MNRCLARA`.`tblclientemailid` (
  `EMAIL_ID` INTEGER AUTO_INCREMENT NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CLIENT_ID` NVARCHAR(20) NOT NULL,
  `EMAIL_DATE_TIME` DATETIME NOT NULL,
  `MATTER_NO` NVARCHAR(20) NULL,
  `MAIL_TYP` NVARCHAR(50) NULL,
  `FROM_ADD` NVARCHAR(50) NULL,
  `TO_ADD` NVARCHAR(200) NULL,
  `SUBJECT` NVARCHAR(200) NULL,
  `CC` NVARCHAR(200) NULL,
  `BCC` NVARCHAR(200) NULL,
  `BODY` NVARCHAR(2000) NULL,
  `IS_DELETED` INTEGER NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `EMAIL_ID`, `LANG_ID`, `CLASS_ID`, `CLIENT_ID`, `EMAIL_DATE_TIME`))
  AUTO_INCREMENT = 1
COMMENT = 'CLIENTEMAIL';

-- CLIENTDOCUMENT Table
CREATE TABLE `MNRCLARA`.`tblclientdocumentid` (
  `CLIENT_DOC_ID` BIGINT(255) PRIMARY KEY ,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CLIENT_ID` NVARCHAR(20) NOT NULL,
  `DOC_NO` NVARCHAR(20) NOT NULL,
  `DOC_URL` NVARCHAR(200) NOT NULL,
  `DOC_DATE_TIME` DATETIME NOT NULL,
  `DOC_URL_VER` NVARCHAR(10) NULL,
  `CLIENT_USR_ID` NVARCHAR(20) NULL,
  `MATTER_NO` NVARCHAR(20) NULL,
  `STATUS_ID` INTEGER NULL,
  `SENT_BY` NVARCHAR(50) NULL,
  `SENT_ON` DATETIME NULL,
  `RECEIVED_ON` DATETIME NULL,
  `RESENT_ON` DATETIME NULL,
  `APPROVED_ON` DATETIME NULL,
  `IS_DELETED` INTEGER NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL
  -- PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `CLIENT_ID`, `DOC_NO`, `DOC_URL`, `DOC_DATE_TIME`))
  )
COMMENT = 'CLIENTDOCUMENT';

ALTER TABLE `tblclientdocumentid` 
ADD COLUMN `CLIENT_DOC_ID` BIGINT(255) NOT NULL FIRST,
ADD PRIMARY KEY (`CLIENT_DOC_ID`);

ALTER TABLE `tblclientdocumentid` 
DROP PRIMARY KEY;

-- CLIENTITFORM Table
CREATE TABLE `MNRCLARA`.`tblclientitformid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CLIENT_ID` NVARCHAR(20) NOT NULL,
  `MATTER_NO` NVARCHAR(20) NOT NULL,
  `IT_FORM_ID` INTEGER NOT NULL,
  `IT_FORM_NO` NVARCHAR(20) NOT NULL,
  `STATUS_ID` INTEGER NULL,
  `CASE_CATEGORY_ID` INTEGER NULL,
  `CASE_SUB_CATEGORY_ID` INTEGER NULL,  
  `NOTE_NO` NVARCHAR(20) NOT NULL,
  `SENT_ON` DATETIME NULL,
  `RECEIVED_ON` DATETIME NULL,
  `RESENT_ON` DATETIME NULL,
  `APPROVED_ON` DATETIME NULL,
  `IS_DELETED` INTEGER NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `CLIENT_ID`, `MATTER_NO`, `IT_FORM_ID`, `IT_FORM_NO`))
COMMENT = 'CLIENTITFORM';

-- CLIENTNOTE Table
CREATE TABLE `MNRCLARA`.`tblclientnoteid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CLIENT_ID` NVARCHAR(20) NOT NULL,
  `NOTE_NO` NVARCHAR(20) NOT NULL,
  `NOTE_TEXT` NVARCHAR(1000) NULL,
  `MATTER_NO` NVARCHAR(20) NULL,
  `NOTE_TYP_ID` INTEGER NULL,
  `STATUS_ID` INTEGER NULL,
  `IS_DELETED` INTEGER NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `CLIENT_ID`, `NOTE_NO`))
COMMENT = 'CLIENTNOTE';
