-- Master Scripts

USE MNRCLARA;

-- NOTES Table
CREATE TABLE `MNRCLARA`.`tblnotesid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `TRANS_ID` INTEGER NOT NULL,
  `TRANS_NO` NVARCHAR(20) NOT NULL,  
  `NOTE_TYP_ID` INTEGER NULL,  
  `NOTE_NO` NVARCHAR(20) NOT NULL,
  `NOTE_TEXT` NVARCHAR(1000) NULL,
  `MATTER_NO` NVARCHAR(20) NULL,  
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `TRANS_ID`, `TRANS_NO`, `NOTE_NO`))
COMMENT = 'NOTES';


-- INQUIRY Table
CREATE TABLE `MNRCLARA`.`tblinquiryid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `INQ_NO` NVARCHAR(20) NOT NULL,
  `EMAIL_ID` NVARCHAR(100) NOT NULL,
  `ALT_EMAIL_ID` NVARCHAR(100) NULL,
  `CONT_NO` NVARCHAR(30) NOT NULL,  
  `INQ_MODE_ID` INTEGER NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `TRANS_ID` INTEGER NULL,
  `IT_FORM_ID` INTEGER NULL,
  `IT_NOTE_NO` NVARCHAR(20) NULL,
  `INQ_DATE` DATETIME NULL,
  `FIRST_NM` NVARCHAR(100) NULL,
  `LAST_NM` NVARCHAR(100) NULL,
  `STATUS_ID` INTEGER NOT NULL,
  `INQ_NOTE_NO` NVARCHAR(20) NULL,
  `ASSIGNED_USR_ID` NVARCHAR(20) NULL,  
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL, 
  `REF_FIELD_11` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  `ASSIGN_BY` NVARCHAR(50) NOT NULL,
  `ASSIGN_ON` DATETIME NOT NULL,
  PRIMARY KEY ( `LANG_ID`, `INQ_NO`, `EMAIL_ID`, `CONT_NO`, `INQ_MODE_ID`, `CLASS_ID`))
COMMENT = 'INQUIRY';

ALTER TABLE `MNRCLARA`.`tblinquiryid` 
CHANGE COLUMN `ref_field_9` `ref_field_9` VARCHAR(1000) NULL DEFAULT NULL ;


-- PCINTAKEFORM Table
CREATE TABLE `MNRCLARA`.`tblpcintakeformid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `INQ_NO` NVARCHAR(20) NOT NULL,
  `IT_FORM_ID` INTEGER NOT NULL,
  `IT_FORM_NO` NVARCHAR(20) NOT NULL,
  `TRANS_ID` INTEGER NULL,
  `EMAIL_ID` NVARCHAR(100) NULL,
  `ALT_EMAIL_ID` NVARCHAR(100) NULL,
  `STATUS_ID` INTEGER NOT NULL,
  `IT_NOTE_NO` NVARCHAR(20) NULL,
  `SENT_ON` DATETIME NULL,
  `RECEIVED_ON` DATETIME NULL,
  `RESENT_ON` DATETIME NULL,
  `APPROVED_ON` DATETIME NULL,
  `APPROVED_BY` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `INQ_NO`, `IT_FORM_ID`, `IT_FORM_NO`))
COMMENT = 'PCINTAKEFORM';

ALTER TABLE `MNRCLARA`.`tblpcintakeformid` 
CHANGE COLUMN `ref_field_9` `ref_field_9` VARCHAR(1000) NULL DEFAULT NULL ;


ALTER TABLE `MNRCLARA`.`tblauditlogid` 
CHANGE COLUMN `new_vl` `new_vl` VARCHAR(1000) NULL DEFAULT NULL ;

-- POTENTIALCLIENT Table
CREATE TABLE `MNRCLARA`.`tblpotentialclientid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `POT_CLIENT_ID` NVARCHAR(20) NOT NULL,
  `CLIENT_CAT_ID` INTEGER NULL,
  `INQ_NO` NVARCHAR(20) NOT NULL,
  `CASE_CATEGORY_ID` INTEGER NULL,
  `IT_FORM_ID` INTEGER NOT NULL,
  `IT_FORM_NO` NVARCHAR(20) NOT NULL,
  `TRANS_ID` INTEGER NULL,
  `FIRST_NM` NVARCHAR(100) NULL,
  `LAST_NM` NVARCHAR(100) NULL,
  `FIRST_LAST_NM` NVARCHAR(100) NULL,
  `LAST_FIRST_NM` NVARCHAR(100) NULL,
  `REFERRAL_ID` INTEGER NULL,
  `EMAIL_ID` NVARCHAR(100) NULL,
  `CONT_NO` NVARCHAR(30) NULL,
  `ALT_PHONE_1` NVARCHAR(30) NULL,
  `ALT_PHONE_2` NVARCHAR(30) NULL,
  `ADDRESS_LINE1` NVARCHAR(1000) NULL,
  `ADDRESS_LINE2` NVARCHAR(1000) NULL,
  `ADDRESS_LINE3` NVARCHAR(1000) NULL,
  `CITY` NVARCHAR(100) NULL,
  `STATE` NVARCHAR(100) NULL,
  `COUNTRY` NVARCHAR(30) NULL,
  `ZIP_CODE` NVARCHAR(30) NULL,
  `CONSULT_DATE` NVARCHAR(30) NULL,
  `SSN_ID` NVARCHAR(30) NULL,
  `MAIL_ADDRESS` NVARCHAR(1000) NULL,
  `OCCUPATION` NVARCHAR(100) NULL,
  `PC_NOTE_NO` NVARCHAR(50) NULL,
  `AGREEMENT_CODE` NVARCHAR(10) NULL,
  `AGREEMENT_URL` NVARCHAR(200) NULL,
  `AGREEMENT_URL_VER` INTEGER NULL,
  `STATUS_ID` INTEGER NOT NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `POT_CLIENT_ID`, `INQ_NO`, `IT_FORM_NO`, `IT_FORM_ID`))
COMMENT = 'POTENTIALCLIENT';

ALTER TABLE `MNRCLARA`.`tblpotentialclientid` 
CHANGE COLUMN `pc_note_no` `pc_note_no` VARCHAR(50) NULL DEFAULT NULL ;


-- AGREEMENT Table
CREATE TABLE `MNRCLARA`.`tblagreementid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `AGREEMENT_CODE` NVARCHAR(10) NOT NULL,
  `CLIENT_ID` NVARCHAR(20) NULL,
  `POT_CLIENT_ID` NVARCHAR(20) NOT NULL,
  `INQ_NO` NVARCHAR(20) NOT NULL,
  `CASE_CATEGORY_ID` INTEGER NULL,
  `AGREEMENT_URL` NVARCHAR(200) NOT NULL,
  `AGREEMENT_URL_VER` NVARCHAR(10) NOT NULL,
  `STATUS_ID` INTEGER NOT NULL,
  `TRANS_ID` INTEGER NULL,
  `NOTE_NO` NVARCHAR(20) NULL,
  `EMAIL_ID` NVARCHAR(100) NULL,
  `SENT_ON` DATETIME NULL,
  `RECEIVED_ON` DATETIME NULL,
  `RESENT_ON` DATETIME NULL,
  `APPROVED_ON` DATETIME NULL,  
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `AGREEMENT_CODE`, `POT_CLIENT_ID`, `INQ_NO`, `AGREEMENT_URL`, `AGREEMENT_URL_VER`))
COMMENT = 'AGREEMENT';

-- CLIENTGENERAL Table
CREATE TABLE `MNRCLARA`.`tblclientgeneral` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CLIENT_ID` NVARCHAR(20) NOT NULL,
  `CLIENT_CAT_ID` INTEGER NOT NULL,
  `POT_CLIENT_ID` NVARCHAR(20) NULL,
  `INQ_NO` NVARCHAR(20) NULL,
  `IT_FORM_ID` INTEGER NULL,
  `FIRST_NM` NVARCHAR(100) NULL,
  `LAST_NM` NVARCHAR(100) NULL,
  `FIRST_LAST_NM` NVARCHAR(100) NULL,
  `LAST_FIRST_NM` NVARCHAR(100) NULL,
  `REFERRAL_ID` INTEGER NULL,
  `EMAIL_ID` NVARCHAR(100) NULL,
  `CONT_NO` NVARCHAR(30) NULL,
  `ADDRESS_LINE1` NVARCHAR(1000) NULL,
  `ADDRESS_LINE2` NVARCHAR(1000) NULL,
  `ADDRESS_LINE3` NVARCHAR(1000) NULL,
  `CITY` NVARCHAR(100) NULL,
  `STATE` NVARCHAR(100) NULL,
  `COUNTRY` NVARCHAR(30) NULL,
  `ZIP_CODE` NVARCHAR(30) NULL,
  `CONSULT_DATE` NVARCHAR(30) NULL,
  `SSN_ID` NVARCHAR(30) NULL,
  `MAIL_ADDRESS` NVARCHAR(1000) NULL,
  `OCCUPATION` NVARCHAR(100) NULL,
  `STATUS_ID` INTEGER NOT NULL,
  `TRANS_ID` INTEGER NOT NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `CLIENT_ID`, `CLIENT_CAT_ID`))
COMMENT = 'CLIENTGENERAL';

CREATE TABLE `MNRCLARA`.`tbldocusigntoken` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CLIENT_ID` NVARCHAR(500) NOT NULL,
  `AUTH_TOKEN` NVARCHAR(5000) NOT NULL,
  `REFRESH_TOKEN` NVARCHAR(5000) NOT NULL,
  `EXPIRES_IN` INT NULL,
  `TOKEN_GEN_ON` DATETIME NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,  
  PRIMARY KEY ( `ID`));
  
  CREATE TABLE `MNRCLARA`.`tbldocusigntrans` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CLIENT_ID` NVARCHAR(255) NOT NULL,
  `ACCOUNT_ID` NVARCHAR(255) NULL,
  `ENV_ID` NVARCHAR(255) NULL,
  `DOC_ID` NVARCHAR(255) NULL,
  `SIGNER_NAME` NVARCHAR(255) NULL,
  `SIGNER_EMAIL` NVARCHAR(255) NULL,
  `SENT_ON` NVARCHAR(255) NULL,
  `STATUS` NVARCHAR(255) NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,  
  PRIMARY KEY ( `ID`));
  
ALTER TABLE `MNRCLARA`.`tbldocusigntrans` 
CHANGE COLUMN `ID` `ID` INT AUTO_INCREMENT PRIMARY KEY;

INT(10);

ALTER TABLE MNRCLARA.tbldocusigntoken MODIFY COLUMN CLIENT_ID NVARCHAR(500);
ALTER TABLE MNRCLARA.tbldocusigntoken MODIFY COLUMN AUTH_TOKEN NVARCHAR(7000);
ALTER TABLE MNRCLARA.tbldocusigntoken MODIFY COLUMN REFRESH_TOKEN NVARCHAR(7000);