-- Master Scripts

USE MNRCLARA;

-- LANGUAGE Table
CREATE TABLE `MNRCLARA`.`tbllanguageid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `LANG_TEXT` NVARCHAR(100) NULL,  
  `IS_DELETED` INTEGER NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`))
COMMENT = 'LANGUAGE';


-- SCREEN Table
CREATE TABLE `MNRCLARA`.`tblscreenid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `SCREEN_ID` INTEGER NOT NULL,
  `SUB_SCREEN_ID` INTEGER NOT NULL,
  `SCREEN_TEXT` NVARCHAR(100) NULL,  
  `SUB_SCREEN_TEXT` NVARCHAR(100) NULL,  
  `IS_DELETED` INTEGER NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `SCREEN_ID`, `SUB_SCREEN_ID`))
COMMENT = 'SCREEN';


-- USERTYPE Table
CREATE TABLE `MNRCLARA`.`tblusertypeid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `USR_TYP_ID` INTEGER NOT NULL,
  `USR_TYP_TEXT` NVARCHAR(100) NULL,  
  `IS_DELETED` INTEGER NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `USR_TYP_ID`))
COMMENT = 'USERTYPE';


-- TRANSACTION Table
CREATE TABLE `MNRCLARA`.`tbltransactionid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `TRANS_ID` INTEGER NOT NULL,
  `TRANS_TEXT` NVARCHAR(100) NULL,  
  `IS_DELETED` INTEGER NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `TRANS_ID`))
COMMENT = 'TRANSACTION';


-- CLIENTTYPE Table
CREATE TABLE `MNRCLARA`.`tblclienttypeid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CLIENT_TYP_ID` INTEGER NOT NULL,
  `CLIENT_TYP_TEXT` NVARCHAR(100) NULL,  
  `IS_DELETED` INTEGER NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `CLIENT_TYP_ID`))
COMMENT = 'CLIENTTYPE';


-- STATUS Table
CREATE TABLE `MNRCLARA`.`tblstatusid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `STATUS_ID` INTEGER NOT NULL,
  `STATUS_TEXT` NVARCHAR(100) NULL,  
  `IS_DELETED` INTEGER NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `STATUS_ID`))
COMMENT = 'STATUS';


-- MESSAGE Table
CREATE TABLE `MNRCLARA`.`tblmessageid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `MESSAGE_ID` INTEGER NOT NULL,
  `MESSAGE_TYP` NVARCHAR(5) NOT NULL,
  `MESSAGE_TEXT` NVARCHAR(500) NULL,  
  `IS_DELETED` INTEGER NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `MESSAGE_ID`, `MESSAGE_TYP`))
COMMENT = 'MESSAGE';


-- CLIENTCATEGORY Table
CREATE TABLE `MNRCLARA`.`tblclientcategoryid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CLIENT_CAT_ID` INTEGER NOT NULL,
  `CLIENT_CAT_TEXT` NVARCHAR(100) NULL,  
  `IS_DELETED` INTEGER NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `CLIENT_CAT_ID`))
COMMENT = 'CLIENTCATEGORY';



-- INTAKEFORM Table
CREATE TABLE `MNRCLARA`.`tblintakeformid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CLIENT_TYP_ID` INTEGER NOT NULL,
  `IT_FORM_ID` INTEGER NOT NULL,
  `IT_FORM_TEXT` NVARCHAR(100) NULL,  
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `IS_DELETED` INTEGER NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `CLIENT_TYP_ID`, `IT_FORM_ID`))
COMMENT = 'INTAKEFORM';


-- NOTIFICATION Table
CREATE TABLE `MNRCLARA`.`tblnotificationid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `TRANS_ID` INTEGER NOT NULL,
  `USR_ID` NVARCHAR(20) NOT NULL,
  `NOT_ID` INTEGER NOT NULL,
  `NOT_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INTEGER NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `TRANS_ID`, `USR_ID`, `NOT_ID`))
COMMENT = 'NOTIFICATION';


-- COMPANY Table
CREATE TABLE `MNRCLARA`.`tblcompanyid` (
  `COMP_ID` NVARCHAR(5) NOT NULL, 
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `COMP_TEXT` NVARCHAR(200) NULL,
  `COMP_ADDRESS_1` NVARCHAR(200) NULL,
  `COMP_ADDRESS_2` NVARCHAR(200) NULL,
  `CONTACT_NM` NVARCHAR(50) NULL,
  `CONTACT_NO` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `COMP_ID`, `LANG_ID`))
COMMENT = 'COMPANY';


