
USE MNRCLARA;

Select * from `MNRCLARA`.`tblnumberrangeid`
where class_id=1 and num_ran_code=5;

Update `MNRCLARA`.`tblnumberrangeid` set num_ran_obj='CLIENT - L&E'
where class_id=1 and num_ran_code=5 and num_ran_obj='CLIENTLNE' and Lang_id='EN';

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',3,99,'USERROLE',1,199999,0,0,0,'MNRCLARA', CURDATE());

------------------------------------------------------------------------------------------------------------------------------

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',3,1,'INQUIRY',100001,199999,100000,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',3,2,'NOTES',1000001,1999999,1000001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',3,3,'AUDITLOG','AL100001','AL999999','AL100002',0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',3,4,'POTENTIALCLIENT',2000001,2999999,2000001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',3,7,'INTAKE',30000001,39999999,30000001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',1,5,'CLIENTLNE',500001,599999,500001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',2,6,'CLIENT-IMMIGRATION',10001,99999,10001,0,0,'MNRCLARA', CURDATE());

---------------------------------------------------------------------------------------------------------------------------------------------------------

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',1,8,'LECASEINFOSHEET',4000001,4999999,4000001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',2,9,'IMMCASEINFOSHEET',5000001,5999999,5000001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',1,10,'LETASK',200001,299999,200001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',2,11,'IMMTASK',400001,499999,400001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',1,12,'LETIMETICKET',300001,399999,300001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',2,13,'IMMTIMETICKET',600001,699999,600001,0,0,'MNRCLARA', CURDATE());	

-----------------------------------------------------------------------------------------------------------------------------------------

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',3,8,'MATTERINTAKE',80000001,89999999,80000001,0,0,'MNRCLARA', CURDATE());
------------------------------------------------------------------------------------------------------------------------------------------------------------ Sprint6 - Accounting --
INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',1,10,'LETASK',200001,299999,200001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',2,11,'IMMTASK',400001,499999,400001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',1,12,'LETIMETICKET',300001,399999,300001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',2,13,'IMMTIMETICKET',600001,699999,600001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',3,14,'MATTERINTAKE',8000001,8999999,8000001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',2,15,'QUOTATION',900001,999999,900001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',2,16,'PAYMENTPLAN',6000001,6999999,6000001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',3,17,'PREBILL',700001,799999,700001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',3,18,'INVOICE',800001,899999,800001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',3,19,'CLIENTPORTAL',700001,799999,700001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',3,20,'DOCCHECKLISTID',9000001,9999999,9000001,0,0,'MNRCLARA', CURDATE());

INSERT INTO `MNRCLARA`.`tblnumberrangeid`
(`LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`,`NUM_RAN_OBJ`,`NUM_RAN_FROM`,`NUM_RAN_TO`,`NUM_RAN_CURRENT`,`NUM_RAN_STATUS`,`IS_DELETED`, `CTD_BY`,`CTD_ON`)
VALUES ('EN',3,21,'CLIENTPORTALDOC',10000001,19999999,10000000,0,0,'MNRCLARA', CURDATE());

-----------------------------------------------------------------------------------------------------------------------------------------
-- Conflict Search-----------------------
ALTER TABLE `MNRCLARA`.`tblagreementid` 
DROP INDEX `full_text_search_idx` ,
ADD FULLTEXT INDEX `full_text_search_idx` (`EMAIL_ID`, `AGREEMENT_URL_VER`,
 `AGREEMENT_URL`, `CLIENT_ID`, `AGREEMENT_CODE`) ;

ALTER TABLE `tblpotentialclientid` 
DROP INDEX `full_text_search_idx` ,
ADD FULLTEXT INDEX `full_text_search_idx` (`EMAIL_ID`, `ADDRESS_LINE1`, `ADDRESS_LINE2`, `ADDRESS_LINE3`, `STATE`, `CITY`, `COUNTRY`, `MAIL_ADDRESS`, `OCCUPATION`, `LAST_NM`, `FIRST_LAST_NM`, `LAST_FIRST_NM`, `FIRST_NM`);

ALTER TABLE `MNRCLARA`.`tblmattergenaccid` 
-- DROP INDEX `full_text_search_idx` ,
ADD FULLTEXT INDEX `full_text_search_idx` (`CLIENT_ID`, `MATTER_NO`, `MATTER_TEXT`) ;


ALTER TABLE `tblinvoiceline` ADD FULLTEXT INDEX `full_text_search_idx` (`CLIENT_ID`);

ALTER TABLE `MNRCLARA`.`tblclientgeneralid` 
DROP INDEX `full_text_search_idx` ,
ADD FULLTEXT INDEX `full_text_search_idx` (`FIRST_NM`, `LAST_NM`, `LAST_FIRST_NM`, `FIRST_LAST_NM`, `CLIENT_ID`, `OCCUPATION`, `MAIL_ADDRESS`, `EMAIL_ID`, `COUNTRY`, `CITY`, `ADDRESS_LINE3`, `ADDRESS_LINE2`, `ADDRESS_LINE1`) ;


-------------------Conflict Check-Query-----------------------------------------------------------------------------
SELECT * FROM MNRCLARA.tblclientgeneralid WHERE 
	 MATCH (FIRST_NM, LAST_NM, LAST_FIRST_NM, FIRST_LAST_NM, CLIENT_ID, OCCUPATION, 
	 MAIL_ADDRESS, EMAIL_ID, COUNTRY, CITY, 
	 ADDRESS_LINE3, ADDRESS_LINE2, ADDRESS_LINE1) 
	 AGAINST ('500014')
	 
SELECT * FROM MNRCLARA.tblagreementid 
	WHERE MATCH (EMAIL_ID, AGREEMENT_URL_VER, AGREEMENT_URL, CLIENT_ID, AGREEMENT_CODE)
	AGAINST ('raj@tekclover.com')
	
SELECT * FROM MNRCLARA.tblmattergenaccid WHERE 
	 MATCH (CLIENT_ID, MATTER_NO, MATTER_TEXT) 
	 AGAINST ('500002-01')










