USE MNRCLARA;

-- USERROLE Table
CREATE TABLE `MNRCLARA`.`tbluserroleid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `USR_ROLE_ID` INTEGER NOT NULL,
  `SCREEN_ID` INTEGER NOT NULL,
  `SUB_SCREEN_ID` INTEGER NOT NULL,  
  `USR_ROLE_NM` NVARCHAR(50) NULL,  
  `CREATE_UPDATE` BOOLEAN NULL,
  `VIEW` BOOLEAN NULL,  
  `DELETE` BOOLEAN NULL,  
  `ROLE_STATUS` BOOLEAN NULL,    
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `USR_ROLE_ID`, `SCREEN_ID`, `SUB_SCREEN_ID`))
COMMENT = 'USERROLE';

-- USERPROFILE Table
CREATE TABLE `MNRCLARA`.`tbluserprofileid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `USR_ID` NVARCHAR(20) NOT NULL,
  `USR_ROLE_ID` INTEGER NOT NULL,
  `PASSWORD` NVARCHAR(255) NOT NULL,
  `USR_TYP_ID` INTEGER NOT NULL,
  `FST_NM` NVARCHAR(50) NULL,
  `LST_NM` NVARCHAR(50) NULL,
  `FULL_NM` NVARCHAR(100) NULL,
  `USR_STATUS` NVARCHAR(50) NULL,
  `EMAIL_ID` NVARCHAR(100) NULL,
  `PHONE_NO` NVARCHAR(20) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50)NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY (`USR_ID`))
COMMENT = 'USERPROFILE';


-- USER_OTP Table
CREATE TABLE `MNRCLARA`.`tbluserotp` (
  `USR_ID` NVARCHAR(20) NOT NULL,
  `OTP_CODE` INTEGER NOT NULL,
  `OTP_SENT_TIME` DATETIME NOT NULL, 
  `USR_LOG_TIME` DATETIME NULL,
  `OTP_STATUS` NVARCHAR(20) NOT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL);
COMMENT = 'USER_OTP';

-- TIMEKEEPERCODE Table
CREATE TABLE `MNRCLARA`.`tbltimekeepercodeid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `TK_CODE` NVARCHAR(10) PRIMARY KEY NOT NULL,
  `USR_TYP_ID` INTEGER NOT NULL,
  `DEF_RATE` DECIMAL (20,2) NOT NULL,
  `TK_NAME` NVARCHAR(50) NULL, 
  `RATE_UNIT` NVARCHAR(5) NULL,
  `TK_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50)NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL
  
   -- PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `TK_CODE`, `USR_TYP_ID`, `DEF_RATE`)
   )
COMMENT = 'TIMEKEEPERCODE';

-- CLASS Table
CREATE TABLE `MNRCLARA`.`tblclassid` (
  `CLASS_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS` NVARCHAR(20) NOT NULL,
  `COMP_ID` NVARCHAR(5) NOT NULL,
  `CL_STATUS` NVARCHAR(50) NULL, 
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `CLASS_ID`))
COMMENT = 'CLASS';

-- CASECATEGORY Table
CREATE TABLE `MNRCLARA`.`tblcasecategoryid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CASE_CATEGORY_ID` INTEGER NOT NULL,
  `CASE_CATEGORY` NVARCHAR(20) NOT NULL,
  `CATEGORY_TEXT` NVARCHAR(100) NULL,
  `TAX_TYPE` NVARCHAR(20) NULL,
  `CATEGORY_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `CASE_CATEGORY_ID`, `CASE_CATEGORY`))
COMMENT = 'CASECATEGORY';

-- CASESUBCATEGORY Table
CREATE TABLE `MNRCLARA`.`tblcasesubcategoryid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CASE_CATEGORY_ID` INTEGER NOT NULL,
  `CASE_SUB_CATEGORY_ID` INTEGER NOT NULL,  
  `CASE_SUB_CATEGORY` NVARCHAR(20) NOT NULL,
  `SUB_CATEGORY_TEXT` NVARCHAR(100) NULL,
  `TAX_TYPE` NVARCHAR(20) NULL,
  `CATEGORY_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `CASE_CATEGORY_ID`, `CASE_SUB_CATEGORY_ID`, `CASE_SUB_CATEGORY`))
COMMENT = 'CASESUBCATEGORY';

-- ACTIVITYCODE Table
CREATE TABLE `MNRCLARA`.`tblactivitycodeid` (
  `ACT_CODE_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `ACT_CODE` NVARCHAR(20) NOT NULL,
  `ACT_TEXT` NVARCHAR(100) NULL,  
  `ACT_CODE_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `ACT_CODE_ID`))
COMMENT = 'ACTIVITYCODE';

-- TASKBASEDCODE Table
CREATE TABLE `MNRCLARA`.`tbltaskbasecodeid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `TASK_CODE` NVARCHAR(20) NOT NULL,
  `TASK_TEXT` NVARCHAR(100) NULL,  
  `TASK_CODE_TYP` NVARCHAR(10) NULL,
  `SUM_LEVEL` BOOLEAN NULL,
  `TASK_CODE_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `TASK_CODE`))
COMMENT = 'TASKBASEDCODE';

-- CHARTOFACCOUNTS Table
CREATE TABLE `MNRCLARA`.`tblchartofaccountsid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `ACCOUNT_NO` NVARCHAR(20) NOT NULL,
  `ACCOUNT_TEXT` NVARCHAR(100) NULL,  
  `ACC_TYP` NVARCHAR(50) NULL,
  `INCOME_TAX_LINE` NVARCHAR(100) NULL,
  `ACC_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `ACCOUNT_NO`))
COMMENT = 'CHARTOFACCOUNTS';

-- EXPENSECODE Table
CREATE TABLE `MNRCLARA`.`tblexpensecodeid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `EXP_CODE` NVARCHAR(20) NOT NULL,
  `COST_TYP` NVARCHAR(20) NULL,  
  `COST_ITEM` DECIMAL(20,2) NULL,
  `EXP_CODE_TEXT` NVARCHAR(100) NULL,
  `RATE_UNIT` NVARCHAR(5) NULL,
  `EXP_CODE_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY (`EXP_CODE`))
COMMENT = 'EXPENSECODE';


-- TASKTYPE Table
CREATE TABLE `MNRCLARA`.`tbltasktypeid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `TASK_TYP_CODE` INTEGER NOT NULL,
  `TASK_TYP_CODE_TEXT` NVARCHAR(100) NULL,  
  `TASK_TYP_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `TASK_TYP_CODE`))
COMMENT = 'TASKTYPE';

-- ADMINCOST Table
CREATE TABLE `MNRCLARA`.`tbladmincostid` (
  -- `ADMIN_COST_ID` INTEGER NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `FLAT_FEE_FROM` DECIMAL(20,2) NOT NULL,
  `FLAT_FEE_TO` DECIMAL(20,2) NOT NULL,  
  `ADMIN_COST` DECIMAL(20,2) NOT NULL,
  `RATE_UNIT` NVARCHAR(5) NULL,
  `TARIFF_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL
  
  -- PRIMARY KEY ( `ADMIN_COST_ID`)
  )
COMMENT = 'ADMINCOST';

-- BILLINGMODE Table
CREATE TABLE `MNRCLARA`.`tblbillingmodeid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `BILL_MODE_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `BILL_MODE_TEXT` NVARCHAR(100) NULL,
  `BILL_MODE_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `BILL_MODE_ID`))
COMMENT = 'BILLINGMODE';

-- BILLINGFREQUENCY Table
CREATE TABLE `MNRCLARA`.`tblbillingfrequencyid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `BILL_FREQ_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `BILL_FREQ_TEXT` NVARCHAR(100) NULL,
  `BILL_FREQ_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `BILL_FREQ_ID`))
COMMENT = 'BILLINGFREQUENCY';


ALTER TABLE `MNRCLARA`.`tblbillingfrequencyid` 
CHANGE COLUMN `bill_freq_id` `bill_freq_id` BIGINT NOT NULL AUTO_INCREMENT,
CHANGE COLUMN `class_id` `class_id` INT NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(255) NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`bill_freq_id`);


-- BILLINGFORMAT Table
CREATE TABLE `MNRCLARA`.`tblbillingformatid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `BILL_FORMAT_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `BILL_FORMAT_TEXT` NVARCHAR(100) NULL,
  `BILL_FORMAT_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `BILL_FORMAT_ID`))
COMMENT = 'BILLINGFORMAT';

ALTER TABLE `MNRCLARA`.`tblbillingformatid` 
CHANGE COLUMN `bill_format_id` `bill_format_id` INT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `class_id` `class_id` BIGINT NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(20) NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`bill_format_id`);

-- DEADLINECALCULATOR Table
CREATE TABLE `MNRCLARA`.`tbldeadlinecalculatorid` (
  `DEADLINE_CALC_ID` BIGINT(255) PRIMARY KEY,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CASE_CATEGORY_ID` INTEGER NULL,
  `TASK_TYP_CODE` NVARCHAR(20) NOT NULL,
  `DEADLINE_DAYS` INTEGER NULL,
  `DEADLINE_DAYS_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL
  )
COMMENT = 'DEADLINECALCULATOR';


-- NUMBERRANGE Table
CREATE TABLE `MNRCLARA`.`tblnumberrangeid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `NUM_RAN_CODE` INTEGER NOT NULL,
  `NUM_RAN_OBJ` NVARCHAR(100) NOT NULL,
  `NUM_RAN_FROM` NVARCHAR(255) NULL,
  `NUM_RAN_TO` NVARCHAR(255) NULL,
  `NUM_RAN_CURRENT` NVARCHAR(255) NULL,
  `NUM_RAN_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `NUM_RAN_CODE`, `NUM_RAN_OBJ`))
COMMENT = 'NUMBERRANGE';

-- AGREEMENTTEMPLATE Table
CREATE TABLE `MNRCLARA`.`tblagreementtemplateid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CASE_CATEGORY_ID` INTEGER NOT NULL,
  `AGREEMENT_CODE` NVARCHAR(10) NOT NULL,
  `AGREEMENT_URL` NVARCHAR(200) NOT NULL,
  `MAIL_MERGE` BOOLEAN NOT NULL,
  `AGREEMENT_TEXT` NVARCHAR(100) NULL,
  `AGREEMENT_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `CASE_CATEGORY_ID`, `AGREEMENT_CODE`, `AGREEMENT_URL`))
COMMENT = 'AGREEMENTTEMPLATE';

ALTER TABLE `MNRCLARA`.`tblagreementtemplateid` 
CHANGE COLUMN `agreement_code` `agreement_code` VARCHAR(10) NOT NULL,
CHANGE COLUMN `class_id` `class_id` BIGINT NULL ,
CHANGE COLUMN `case_category_id` `case_category_id` BIGINT NULL ,
CHANGE COLUMN `agreement_url` `agreement_url` VARCHAR(200) NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(20) NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`agreement_code`);

-- DOCUMENTTEMPLATE Table
CREATE TABLE `MNRCLARA`.`tbldocumenttemplateid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CASE_CATEGORY_ID` INTEGER NOT NULL,
  `DOC_NO` NVARCHAR(20) NOT NULL PRIMARY KEY ,
  `DOC_URL` NVARCHAR(200) NOT NULL,
  `MAIL_MERGE` BOOLEAN NOT NULL,
  `DOC_TEXT` NVARCHAR(100) NULL,
  `DOC_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL)
COMMENT = 'DOCUMENTTEMPLATE';

ALTER TABLE `MNRCLARA`.`tbldocumenttemplateid` 
CHANGE COLUMN `doc_no` `doc_no` VARCHAR(10) NOT NULL,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`doc_no`);


-- CLIENTUSER Table
CREATE TABLE `MNRCLARA`.`tblclientuserid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `CLIENT_USR_ID` NVARCHAR(20) NOT NULL,
  `PASSWORD` NVARCHAR(30) NOT NULL,
  `CLIENT_CAT_ID` INTEGER NOT NULL,
  `FST_NM` NVARCHAR(50) NULL,
  `LST_NM` NVARCHAR(50) NULL,
  `FULL_NM` NVARCHAR(100) NULL,
  `CLIENT_USR_STATUS` NVARCHAR(50) NULL,
  `EMAIL_ID` NVARCHAR(100) NULL,
  `PHONE_NO` NVARCHAR(20) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `CLIENT_USR_ID`, `PASSWORD`, `CLIENT_CAT_ID`))
COMMENT = 'CLIENTUSER';


-- INQUIRYMODE Table
CREATE TABLE `MNRCLARA`.`tblinquirymodeid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `INQ_MODE_ID` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
  `INQ_MODE_TEXT` NVARCHAR(100) NULL,
  `INQ_MODE_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL)
COMMENT = 'INQUIRYMODE';

---------------------------------------------------------------------------------------------

-- REFERRAL Table
CREATE TABLE `MNRCLARA`.`tblreferralid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `REFERRAL_ID` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `SUB_REFERRAL_ID` INTEGER NOT NULL,
  `REFERRAL_TEXT` NVARCHAR(100) NULL,
  `SUB_REFERRAL_TEXT` NVARCHAR(100) NULL,
  `REFERRAL_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL)
COMMENT = 'REFERRAL';

---------------------------------------------------------------------------------------------


-- NOTETYPE Table
CREATE TABLE `MNRCLARA`.`tblnotetypeid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `NOTE_TYP_ID` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `NOTE_TYP_TEXT` NVARCHAR(100) NULL,
  `NOTE_TYP_STATUS` NVARCHAR(50) NULL,
  `IS_DELETED` INTEGER NOT NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `NOTE_TYP_ID`))
COMMENT = 'NOTETYPE';

---------------------------------------------------------------------------------------------

-- AUDITLOG Table
CREATE TABLE `MNRCLARA`.`tblauditlogid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `AUD_LOG_NO` NVARCHAR(20) NOT NULL,
  `TRANS_ID` INTEGER NOT NULL,
  `TRANS_NO` NVARCHAR(20) NOT NULL,
  `TABLE_NM` NVARCHAR(50) NULL,
  `MOD_FIELD` NVARCHAR(50) NULL,
  `OLD_VL` NVARCHAR(50) NULL,
  `NEW_VL` NVARCHAR(50) NULL,  
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,  
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,  
  `REF_FIELD_5` NVARCHAR(200) NULL,  
  `REF_FIELD_6` NVARCHAR(200) NULL,  
  `REF_FIELD_7` NVARCHAR(200) NULL,  
  `REF_FIELD_8` NVARCHAR(200) NULL,  
  `REF_FIELD_9` NVARCHAR(200) NULL,  
  `REF_FIELD_10` NVARCHAR(200) NULL,   
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `CLASS_ID`, `AUD_LOG_NO`, `TRANS_ID`,  `TRANS_NO`))
COMMENT = 'AUDITLOG';

----------------------------------------------------------------------------------------------------------------

================================================================================================================
SPRINT 6 changes
-----------------

ALTER TABLE `MNRCLARA`.`tblcasesubcategoryid` 
CHANGE COLUMN `CASE_SUB_CATEGORY` `CASE_SUB_CATEGORY` VARCHAR(20) CHARACTER SET 'utf8' NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`LANG_ID`, `CLASS_ID`, `CASE_CATEGORY_ID`, `CASE_SUB_CATEGORY_ID`);

-----------------------------------------------------------------------------------------------------------------

CREATE TABLE `MNRCLARA`.`tblexpirationdoctype` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `CLASS_ID` INTEGER NOT NULL,
  `DOC_TYPE` NVARCHAR(20) NOT NULL,
  `DOC_TYP_TEXT` NVARCHAR(1000) NULL,
  `STATUS_ID` NVARCHAR(100) NULL,
  `IS_DELETED` INTEGER NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,
  `REF_FIELD_5` NVARCHAR(200) NULL,
  `REF_FIELD_6` NVARCHAR(200) NULL,
  `REF_FIELD_7` NVARCHAR(200) NULL,
  `REF_FIELD_8` NVARCHAR(200) NULL,
  `REF_FIELD_9` NVARCHAR(200) NULL,
  `REF_FIELD_10` NVARCHAR(200) NULL,
  `CTD_BY` NVARCHAR(50) NOT NULL,
  `CTD_ON` DATETIME NOT NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`LANG_ID`,`CLASS_ID`,`DOC_TYPE`)
);

-- CLIENT USER Table
CREATE TABLE `MNRCLARA`.`tblclientuser` (
	
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`CLASS_ID` INTEGER NOT NULL,
	`CLIENT_USR_ID` NVARCHAR(20) NOT NULL,
	`CLIENT_ID` NVARCHAR(20) NOT NULL,
	`CLIENT_CAT_ID` INTEGER NULL,
	`CONT_NO` NVARCHAR(20) NULL,
	`FIRST_NM` NVARCHAR(50) NULL,
	`LAST_NM` NVARCHAR(50) NULL,
	`FIRST_LAST_NM` NVARCHAR(100) NULL,
	`STATUS_ID` NVARCHAR(50) NULL,
	`EMAIL_ID` NVARCHAR(100) NULL,
	`QUOTATION` BOOLEAN NULL,
	`PAYMENTPLAN` BOOLEAN NULL,
	`MATTER` BOOLEAN NULL,
	`DOCUMENT` BOOLEAN NULL,
	`INVOICE` BOOLEAN NULL,
	`AGREEMENT` BOOLEAN NULL,
	`IS_DELETED` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

	PRIMARY KEY (`CLIENT_USR_ID`))
COMMENT = 'CLIENT USER';


-- DOC CHECK LIST Table
CREATE TABLE `MNRCLARA`.`tbldocchecklist` (
	
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`CLASS_ID` INTEGER NOT NULL,
	`CHK_LIST_NO` INTEGER NOT NULL,
	`CASE_CATEGORY_ID` INTEGER NOT NULL,
	`CASE_SUB_CATEGORY_ID` INTEGER NOT NULL,
	`SEQ_NO` INTEGER NOT NULL,
	`DOC_NM` NVARCHAR(50) NULL,
	`DOC_URL` NVARCHAR(50) NULL,
	`STATUS_ID` NVARCHAR(20) NULL,
	`IS_DELETED` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,
	
	PRIMARY KEY (`LANG_ID`, `CLASS_ID`, `CHK_LIST_NO`, `CASE_CATEGORY_ID`, `CASE_SUB_CATEGORY_ID`, `SEQ_NO`))
COMMENT = 'DOC CHECK LIST';


================================================================================================================


ALTER TABLE `MNRCLARA`.`tbluserprofileid`
CHANGE COLUMN `LANG_ID` `LANG_ID` VARCHAR(5) CHARACTER SET 'utf8' NULL ,
CHANGE COLUMN `CLASS_ID` `CLASS_ID` INT NULL ,
CHANGE COLUMN `USR_ROLE_ID` `USR_ROLE_ID` INT NULL ,
CHANGE COLUMN `PASSWORD` `PASSWORD` VARCHAR(255) CHARACTER SET 'utf8' NULL ,
CHANGE COLUMN `USR_TYP_ID` `USR_TYP_ID` INT NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`USR_ID`);

-- ------------------------------------------MASTERS - DB Changes------------------------------------------------------
ALTER TABLE `MNRCLARA`.`tblusertypeid` 
CHANGE COLUMN `CLASS_ID` `CLASS_ID` INT NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(20) NULL ,
CHANGE COLUMN `usr_typ_id` `usr_typ_id` BIGINT NOT NULL AUTO_INCREMENT ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`usr_typ_id`);
---------------------------------------------------------------------------------------------

ALTER TABLE `MNRCLARA`.`tblclienttypeid` 
CHANGE COLUMN `CLASS_ID` `CLASS_ID` INT NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(20) NULL ,
CHANGE COLUMN `client_typ_id` `client_typ_id` BIGINT NOT NULL AUTO_INCREMENT ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`client_typ_id`);

---------------------------------------------------------------------------------------------

ALTER TABLE `MNRCLARA`.`tblclientcategoryid` 
CHANGE COLUMN `class_id` `class_id` INT NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(20) NULL ,
CHANGE COLUMN `client_cat_id` `client_cat_id` BIGINT NOT NULL AUTO_INCREMENT ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`client_cat_id`);

---------------------------------------------------------------------------------------------

ALTER TABLE `MNRCLARA`.`tblintakeformid` 
CHANGE COLUMN `it_form_id` `it_form_id` BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `class_id` `class_id` INT NULL ,
CHANGE COLUMN `client_typ_id` `client_typ_id` BIGINT NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(20) NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`it_form_id`);

---------------------------------------------------------------------------------------------

ALTER TABLE `MNRCLARA`.`tblnotificationid` 
CHANGE COLUMN `not_id` `not_id` BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `class_id` `class_id` INT NULL ,
CHANGE COLUMN `trans_id` `trans_id` BIGINT NULL ,
CHANGE COLUMN `usr_id` `usr_id` VARCHAR(20) NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(20) NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`not_id`);

---------------------------------------------------------------------------------------------

ALTER TABLE `MNRCLARA`.`tblclassid` 
CHANGE COLUMN `class_id` `class_id` BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `class` `class` VARCHAR(20) NULL ,
CHANGE COLUMN `comp_id` `comp_id` VARCHAR(5) NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(20) NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`class_id`);

---------------------------------------------------------------------------------------------

ALTER TABLE `MNRCLARA`.`tblcasecategoryid` 
CHANGE COLUMN `case_category_id` `case_category_id` BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `class_id` `class_id` BIGINT NULL ,
CHANGE COLUMN `case_category` `case_category` VARCHAR(100) NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(20) NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`case_category_id`);

---------------------------------------------------------------------------------------------

ALTER TABLE `MNRCLARA`.`tblcasesubcategoryid` 
CHANGE COLUMN `case_sub_category_id` `case_sub_category_id` BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `class_id` `class_id` BIGINT NULL ,
CHANGE COLUMN `case_category_id` `case_category_id` BIGINT NULL ,
CHANGE COLUMN `case_sub_category` `case_sub_category` VARCHAR(20) NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(20) NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`case_sub_category_id`);

---------------------------------------------------------------------------------------------

ALTER TABLE `MNRCLARA`.`tblexpensecodeid` 
CHANGE COLUMN `exp_code` `exp_code` BIGINT NOT NULL ,
CHANGE COLUMN `class_id` `class_id` BIGINT NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(20) NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`exp_code`);

---------------------------------------------------------------------------------------------

ALTER TABLE `MNRCLARA`.`tbltasktypeid` 
CHANGE COLUMN `task_typ_code` `task_typ_code` BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `class_id` `class_id` BIGINT NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(20) NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`task_typ_code`);

---------------------------------------------------------------------------------------------

ALTER TABLE `MNRCLARA`.`tbladmincostid` 
CHANGE COLUMN `class_id` `class_id` BIGINT NULL ,
CHANGE COLUMN `flat_fee_from` `flat_fee_from` DOUBLE NULL ,
CHANGE COLUMN `flat_fee_to` `flat_fee_to` DOUBLE NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(255) NULL ,
CHANGE COLUMN `admin_cost` `admin_cost` DOUBLE NULL ,
ADD COLUMN `admin_cost_id` INT NOT NULL AUTO_INCREMENT AFTER `admin_cost`,
-- DROP PRIMARY KEY,
ADD PRIMARY KEY (`admin_cost_id`);

--------------------------------------------------------------------------------------------

ALTER TABLE `MNRCLARA`.`tblbillingmodeid` 
CHANGE COLUMN `bill_mode_id` `bill_mode_id` INT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `class_id` `class_id` INT NULL ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(20) NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`bill_mode_id`);

---------------------------------------------------------------------------------------------

ALTER TABLE `MNRCLARA`.`tblglmappingmaster` 
CHANGE COLUMN `item_no` `item_no` BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `lang_id` `lang_id` VARCHAR(20) NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`item_no`);

---------------------------------------------------------------------------------------------
ALTER TABLE `MNRCLARA`.`tblcasecategoryid` 
CHANGE COLUMN `case_category` `case_category` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `MNRCLARA`.`tblcasesubcategoryid` 
CHANGE COLUMN `case_sub_category` `case_sub_category` VARCHAR(100) NULL DEFAULT NULL ;