ALTER TABLE `mnrclara`.`tblclientnoteid` 
ADD COLUMN `ADD_FIELDS_1` VARCHAR(10) NULL AFTER `UTD_ON`,
ADD COLUMN `ADD_FIELDS_2` VARCHAR(200) NULL AFTER `ADD_FIELDS_1`,
ADD COLUMN `ADD_FIELDS_3` VARCHAR(200) NULL AFTER `ADD_FIELDS_2`,
ADD COLUMN `ADD_FIELDS_4` VARCHAR(100) NULL AFTER `ADD_FIELDS_3`,
ADD COLUMN `ADD_FIELDS_5` VARCHAR(200) NULL AFTER `ADD_FIELDS_4`,
ADD COLUMN `ADD_FIELDS_6` VARCHAR(100) NULL AFTER `ADD_FIELDS_5`,
ADD COLUMN `ADD_FIELDS_7` VARCHAR(25) NULL AFTER `ADD_FIELDS_6`;