package com.clara.client.model

import com.google.gson.annotations.SerializedName

data class CheckListResponse(
    @SerializedName("matterHeaderId") var matterHeaderId: Int? = null,
    @SerializedName("languageId") var languageId: String? = null,
    @SerializedName("classId") var classId: Int? = null,
    @SerializedName("checkListNo") var checkListNo: Int? = null,
    @SerializedName("matterNumber") var matterNumber: String? = null,
    @SerializedName("clientId") var clientId: String? = null,
    @SerializedName("matterText") var matterText: String? = null,
    @SerializedName("caseCategoryId") var caseCategoryId: Int? = null,
    @SerializedName("caseSubCategoryId") var caseSubCategoryId: Int? = null,
    @SerializedName("sentBy") var sentBy: String? = null,
    @SerializedName("sentDate") var sentDate: String? = null,
    @SerializedName("receivedDate") var receivedDate: String? = null,
    @SerializedName("resentDate") var resentDate: String? = null,
    @SerializedName("approvedDate") var approvedDate: String? = null,
    @SerializedName("statusId") var statusId: Int? = null,
    @SerializedName("matterDocLists") var matterDocLists: List<MatterDocLists> = listOf(),
    @SerializedName("deletionIndicator") var deletionIndicator: Int? = null,
    @SerializedName("referenceField1") var referenceField1: String? = null,
    @SerializedName("referenceField2") var referenceField2: String? = null,
    @SerializedName("referenceField3") var referenceField3: String? = null,
    @SerializedName("referenceField4") var referenceField4: String? = null,
    @SerializedName("referenceField5") var referenceField5: String? = null,
    @SerializedName("referenceField6") var referenceField6: String? = null,
    @SerializedName("referenceField7") var referenceField7: String? = null,
    @SerializedName("referenceField8") var referenceField8: String? = null,
    @SerializedName("referenceField9") var referenceField9: String? = null,
    @SerializedName("referenceField10") var referenceField10: String? = null,
    @SerializedName("receivedOn") var receivedOn: String? = null,
    @SerializedName("createdBy") var createdBy: String? = null,
    @SerializedName("createdOn") var createdOn: String? = null,
    @SerializedName("updatedBy") var updatedBy: String? = null,
    @SerializedName("updatedOn") var updatedOn: String? = null,
    var isExpand: Boolean = false
)

data class MatterDocLists(
    @SerializedName("matterLineId") var matterLineId: Int? = null,
    @SerializedName("matterHeaderId") var matterHeaderId: Int? = null,
    @SerializedName("languageId") var languageId: String? = null,
    @SerializedName("classId") var classId: Int? = null,
    @SerializedName("checkListNo") var checkListNo: Int? = null,
    @SerializedName("matterNumber") var matterNumber: String? = null,
    @SerializedName("documentUrl") var documentUrl: String? = null,
    @SerializedName("clientId") var clientId: String? = null,
    @SerializedName("sequenceNumber") var sequenceNumber: Int? = null,
    @SerializedName("documentName") var documentName: String? = null,
    @SerializedName("matterText") var matterText: String? = null,
    @SerializedName("caseCategoryId") var caseCategoryId: Int? = null,
    @SerializedName("caseSubCategoryId") var caseSubCategoryId: Int? = null,
    @SerializedName("statusId") var statusId: Int? = null,
    @SerializedName("deletionIndicator") var deletionIndicator: Int? = null,
    @SerializedName("referenceField1") var referenceField1: String? = null,
    @SerializedName("referenceField2") var referenceField2: String? = null,
    @SerializedName("referenceField3") var referenceField3: String? = null,
    @SerializedName("referenceField4") var referenceField4: String? = null,
    @SerializedName("referenceField5") var referenceField5: String? = null,
    @SerializedName("createdBy") var createdBy: String? = null,
    @SerializedName("createdOn") var createdOn: String? = null,
    @SerializedName("updatedBy") var updatedBy: String? = null,
    @SerializedName("updatedOn") var updatedOn: String? = null,
    var isExpand: Boolean = false
)
