package com.clara.client.model

import com.google.gson.annotations.SerializedName

data class QuotationResponse(
    @SerializedName("languageId") var languageId: String? = null,
    @SerializedName("classId") var classId: Int? = null,
    @SerializedName("matterNumber") var matterNumber: String? = null,
    @SerializedName("clientId") var clientId: String? = null,
    @SerializedName("caseCategoryId") var caseCategoryId: Int? = null,
    @SerializedName("caseSubCategoryId") var caseSubCategoryId: Int? = null,
    @SerializedName("quotationNo") var quotationNo: String? = null,
    @SerializedName("quotationRevisionNo") var quotationRevisionNo: String? = null,
    @SerializedName("quotationDate") var quotationDate: String? = null,
    @SerializedName("quotationAmount") var quotationAmount: Int? = null,
    @SerializedName("currency") var currency: String? = null,
    @SerializedName("corporation") var corporation: String? = null,
    @SerializedName("dueDate") var dueDate: String? = null,
    @SerializedName("paymentPlanNumber") var paymentPlanNumber: String? = null,
    @SerializedName("termDetails") var termDetails: String? = null,
    @SerializedName("sentDate") var sentDate: String? = null,
    @SerializedName("approvedDate") var approvedDate: String? = null,
    @SerializedName("statusId") var statusId: Int? = null,
    @SerializedName("deletionIndicator") var deletionIndicator: Int? = null,
    @SerializedName("referenceField1") var referenceField1: String? = null,
    @SerializedName("referenceField2") var referenceField2: String? = null,
    @SerializedName("referenceField3") var referenceField3: String? = null,
    @SerializedName("referenceField4") var referenceField4: String? = null,
    @SerializedName("referenceField5") var referenceField5: String? = null,
    @SerializedName("referenceField6") var referenceField6: String? = null,
    @SerializedName("referenceField7") var referenceField7: String? = null,
    @SerializedName("referenceField8") var referenceField8: String? = null,
    @SerializedName("referenceField9") var referenceField9: String? = null,
    @SerializedName("referenceField10") var referenceField10: String? = null,
    @SerializedName("createdBy") var createdBy: String? = null,
    @SerializedName("createdOn") var createdOn: String? = null,
    @SerializedName("updatedBy") var updatedBy: String? = null,
    @SerializedName("updatedOn") var updatedOn: String? = null,
    @SerializedName("quotationLine") var quotationLine: String? = null,
    var isExpand: Boolean = false
)
