<<<<<<< HEAD
#server.port=8086
server.port=8186
=======
server.port=8086
>>>>>>> 81dc64bb940937a238631ec1ef8d3af347b8ec9e

server.servlet.context-path=/classicwms

spring.datasource.url=jdbc:sqlserver://35.154.84.178;databaseName=WMS
<<<<<<< HEAD
spring.datasource.username=SA
=======
spring.datasource.username=sa
>>>>>>> 81dc64bb940937a238631ec1ef8d3af347b8ec9e
spring.datasource.password=30NcyBuK
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=false
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=50
spring.jpa.hibernate.ddl-auto=update

#----------------Spring - Mongo Configuration----------------------
spring.data.mongodb.host=35.154.84.178
spring.data.mongodb.port=27017
spring.data.mongodb.database=WMS

#-----------Batch Configurtion-------------------------------------
spring.batch.initialize-schema=always
spring.batch.job.enabled=false
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

#security
<<<<<<< HEAD
security.oauth2.resource.filter-order=3

#----------------Spring - Mail Configuration----------------------
spring.mail.protocol=smtp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sankar123aakash@gmail.com
spring.mail.password=msroexuncmqrjcje
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
email.from.address=sankar123aakash@gmail.com 
=======
security.oauth2.resource.filter-order=3
>>>>>>> 81dc64bb940937a238631ec1ef8d3af347b8ec9e
