USE WMS_ALMDEV
GO

CREATE OR ALTER PROCEDURE amghara_staging_line_update_new_proc 
	@companyCodeId nvarchar(5), 
	@plantId nvarchar(5), 
	@languageId nvarchar(5),
	@warehouseId nvarchar(5), 
	@refDocNumber nvarchar(25),
	@preInboundNo nvarchar(25),
	@lineNumber int,
	@itmCode nvarchar(50),	
	@mfrName nvarchar(20),	
	@updatedOn DATETIME
AS
BEGIN
		
	UPDATE IBL SET IBL.REC_ACCEPT_QTY = X.ACCEPTQTY, 
				   IBL.REC_DAMAGE_QTY = X.DAMAGEQTY, 
				   IBL.ST_UTD_ON = @updatedOn, IBL.ST_CNF_ON = @updatedOn				   
	FROM tblstagingline IBL INNER JOIN
	(SELECT C_ID,PLANT_ID,LANG_ID,WH_ID,REF_DOC_NO,PRE_IB_NO,IB_LINE_NO,ITM_CODE,MFR_NAME,
	SUM(ACCEPT_QTY) ACCEPTQTY,SUM(DAMAGE_QTY) DAMAGEQTY
	FROM tblgrline
	WHERE IS_DELETED = 0 AND C_ID = @companyCodeId AND PLANT_ID = @plantId AND LANG_ID = @languageId AND 
		  WH_ID = @warehouseId AND REF_DOC_NO = @refDocNumber AND PRE_IB_NO = @preInboundNo 
		  AND IB_LINE_NO = @lineNumber AND ITM_CODE = @itmCode AND MFR_NAME = @mfrName
		  GROUP BY ITM_CODE,MFR_NAME,IB_LINE_NO,REF_DOC_NO,PRE_IB_NO,WH_ID,PLANT_ID,C_ID,LANG_ID
	) X ON
	IBL.C_ID = X.C_ID AND IBL.PLANT_ID = X.PLANT_ID AND IBL.LANG_ID = X.LANG_ID AND IBL.WH_ID = X.WH_ID AND 
	IBL.REF_DOC_NO = X.REF_DOC_NO AND IBL.PRE_IB_NO = X.PRE_IB_NO AND IBL.ITM_CODE = X.ITM_CODE AND 
	IBL.MFR_NAME = X.MFR_NAME AND IBL.IB_LINE_NO = X.IB_LINE_NO AND IBL.IS_DELETED = 0

	UPDATE IBL SET IBL.STATUS_ID = X.STATUS_ID, IBL.STATUS_TEXT = X.STATUS_TEXT
	FROM tblstagingline IBL INNER JOIN
	(SELECT C_ID,PLANT_ID,LANG_ID,WH_ID,REF_DOC_NO,PRE_IB_NO,IB_LINE_NO,ITM_CODE,MFR_NAME,
	STATUS_ID,STATUS_TEXT
	FROM tblgrline
	WHERE IS_DELETED = 0 AND C_ID = @companyCodeId AND PLANT_ID = @plantId AND LANG_ID = @languageId AND 
		  WH_ID = @warehouseId AND REF_DOC_NO = @refDocNumber AND PRE_IB_NO = @preInboundNo AND STATUS_ID <> 24 AND
		  IB_LINE_NO = @lineNumber AND ITM_CODE = @itmCode AND MFR_NAME = @mfrName AND
		  GR_CTD_ON IN (SELECT MAX(GR_CTD_ON) FROM TBLGRLINE GROUP BY ITM_CODE,MFR_NAME,IB_LINE_NO,REF_DOC_NO,PRE_IB_NO)
	) X ON
	IBL.C_ID = X.C_ID AND IBL.PLANT_ID = X.PLANT_ID AND IBL.LANG_ID = X.LANG_ID AND IBL.WH_ID = X.WH_ID AND 
	IBL.REF_DOC_NO = X.REF_DOC_NO AND IBL.PRE_IB_NO = X.PRE_IB_NO AND IBL.ITM_CODE = X.ITM_CODE AND 
	IBL.MFR_NAME = X.MFR_NAME AND IBL.IB_LINE_NO = X.IB_LINE_NO AND IBL.IS_DELETED = 0
	
END	
GO