#remote
server.port=8182
#server.port=8282
server.servlet.context-path=/classicwms/api/wms-masters-service

#--------------data-source configurations--------------------------

spring.datasource.url=jdbc:sqlserver://43.230.156.163;databaseName=JAIN_CORD
spring.datasource.username=sa
spring.datasource.password=TTPL@123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=false
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update

#security
security.oauth2.resource.filter-order=3

#----------------Spring - Mail Configuration----------------------
spring.mail.protocol=smtp
#spring.mail.host=smtp.gmail.com
#spring.mail.host=smtp.office365.com
spring.mail.host=mail.almailemgroup.com
spring.mail.port=587
spring.mail.username=wmsnotification@almailemgroup.com
spring.mail.password=wL5?aB~8o2!v

# Other properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=25000
spring.mail.properties.mail.smtp.timeout=25000
spring.mail.properties.mail.smtp.writetimeout=25000

# TLS , port 587
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

# Log file location
logging.file.name=logs/masters.log
# Log level for your application (default is INFO)
logging.level.root=INFO
# The filename pattern used to create log archives.
logging.logback.rollingpolicy.file-name-pattern=logs/%d{yyyy-MM}/masters.%d{yyyy-MM-dd}.%i.log
# The maximum size of a log file before it is archived.
logging.logback.rollingpolicy.max-file-size=100MB
# The maximum size of all archived log files before older ones are deleted.
logging.logback.rollingpolicy.total-size-cap=10GB
# The maximum number of archive log files to keep.
logging.logback.rollingpolicy.max-history=10