package com.tekclover.wms.core.model.transaction;

import lombok.Data;
import java.util.Date;

@Data
public class PickListLine {

	private Long pickListCancelLineId;
	private Long pickListCancelHeaderId;
	private String languageId;
	private String companyCodeId;
	private String plantId;
	private String warehouseId;
	private String oldPreOutboundNo;
	private String newPreOutboundNo;
	private String oldRefDocNumber;
	private String newRefDocNumber;
	private String partnerCode;
	private Long oldLineNo;
	private Long newLineNo;
	private String itemCode;
	private String deliveryOrderNo;
	private String batchSerialNumber;
	private Long outboundOrderTypeId;
//	private Long statusId;
	private Long stockTypeId;
	private Long specialStockIndicatorId;
	private String description;
	private Double oldOrderQty;
	private Double newOrderQty;
	private String orderUom;
	private Double deliveryQty;
	private Double oldPickConfirmQty;
	private String oldPickedStorageBin;
	private Double newPickConfirmQty;
	private String newPickedStorageBin;
	private String deliveryUom;
	private String referenceField1;
	private String referenceField2;
	private String referenceField3;
	private String referenceField4;
	private String referenceField5;
	private String referenceField6;
	private String referenceField7;
	private String referenceField8;
	private String referenceField9;
	private String referenceField10;
	private Long deletionIndicator;
	private String createdBy;
	private Date createdOn = new Date();
	private String deliveryConfirmedBy;
	private Date deliveryConfirmedOn;
	private String updatedBy;
	private Date updatedOn;
	private String reversedBy;
	private Date reversedOn;
	private String companyDescription;
	private String plantDescription;
	private String warehouseDescription;
	private String oldStatusDescription;
	private String newStatusDescription;
	private String manufacturerName;
	private Long middlewareId;
	private Long middlewareHeaderId;
	private String middlewareTable;
	private String referenceDocumentType;
	private String supplierInvoiceNo;
	private String salesOrderNumber;
	private String manufacturerFullName;
	private String salesInvoiceNumber;
	private String pickListNumber;
	private String tokenNumber;
	private Date invoiceDate;
	private String deliveryType;
	private String customerId;
	private String customerName;
	private String address;
	private String phoneNumber;
	private String alternateNo;
	private String status;
	/*---------------------------------------------------------------------------------------------------------*/
	private String transferOrderNo;
	private String returnOrderNo;
	private String isCompleted;
	private String targetBranchCode;
	private String barcodeId;
	private String customerType;
	private String handlingEquipment;
	private Long oldStatusId;
	private Long newStatusId;
	private Integer imsSaleTypeCode;
}