package com.tekclover.wms.core.model.transaction;

import lombok.Data;
import java.util.Date;
import java.util.List;

@Data
public class PickListHeader {

	private Long pickListCancelHeaderId;
	private String languageId;
	private String companyCodeId;
	private String plantId;
	private String warehouseId;
	private String oldPreOutboundNo;
	private String newPreOutboundNo;
	private String oldRefDocNumber;
	private String newRefDocNumber;
	private String partnerCode;
	private String deliveryOrderNo;
	private String referenceDocumentType;
	private Long outboundOrderTypeId;
//	private Long statusId;
	private Date refDocDate;
	private Date requiredDeliveryDate;
	private String referenceField1;
	private String referenceField2;
	private String referenceField3;
	private String referenceField4;
	private String referenceField5;
	private String referenceField6;
	private String referenceField7;
	private String referenceField8;
	private String referenceField9;
	private String referenceField10;
	private Long deletionIndicator;
	private String remarks;
	private String createdBy;
	private Date createdOn;
	private String deliveryConfirmedBy;
	private Date deliveryConfirmedOn;
	private String updatedBy;
	private Date updatedOn;
	private String reversedBy;
	private Date reversedOn;
	private String oldInvoiceNumber;
	private String newInvoiceNumber;
	private String companyDescription;
	private String plantDescription;
	private String warehouseDescription;
	private String oldStatusDescription;
	private String newStatusDescription;
	private Long middlewareId;
	private String middlewareTable;
	private String oldSalesOrderNumber;
	private String newSalesOrderNumber;
	private String oldSalesInvoiceNumber;
	private String newSalesInvoiceNumber;
	private String oldSupplierInvoiceNo;
	private String newSupplierInvoiceNo;
	private String oldPickListNumber;
	private String newPickListNumber;
	private String oldTokenNumber;
	private String newTokenNumber;
	private Date oldInvoiceDate;
	private Date newInvoiceDate;
	private String deliveryType;
	private String oldCustomerId;
	private String newCustomerId;
	private String oldCustomerName;
	private String newCustomerName;
	private String address;
	private String phoneNumber;
	private String alternateNo;
	private String status;
	/*-------------------------------------------------------------------------------------------------*/
	private String fromBranchCode;
	private String targetBranchCode;
	private String isCompleted;
	private String isCancelled;
	private Long oldCountOfOrderedLine;
	private Long oldCountOfPickedLine;
	private Long newCountOfOrderedLine;
	private Long newCountOfPickedLine;
	private Long sumOfPickedQty;
	private String customerType;
	private Long oldStatusId;
	private Long newStatusId;
	private Integer imsSaleTypeCode;
	private String customerCode;
	private String TransferRequestType;
	private List<PickListLine> line;
}