package com.courier.overc360.api.model.lastmile;


import lombok.Data;

import javax.persistence.Column;
import java.util.Date;

@Data
public class Delivery {

    private String languageId;
    private String languageDescription;
    private String companyId;
    private String companyName;
    private String partnerType;
    private String partnerId;
    private String partnerName;
    private String consignmentBagId;
    private String partnerHouseAirwayBill;
    private String incoTerms;
    private String deliveryId;
    private String pieceId;
    private String pieceCount;
    private String statusId;
    private String statusDescription;
    private Date statusTimestamp;
    private String paymentType;
    private String paymentMode;
    private String totalShipmentWeight;
    private String productId;
    private String productName;
    private String serviceTypeId;
    private String serviceTypeName;
    private String houseAirwayBill;
    private String remark;
    private String currency;
    private String packageType;
    private String customerCode;
    private String customerReferenceNumber;
    private String consignmentType;
    private String movementType;
    private String loadType;
    private String description;
    private Double codAmount;
    private String codFavorOf;
    private String codCollectionMode;
    private String priority;
    private String deliveryType;
    private String deliveryOtp;
    private String rtoOtp;
    private String deliveryServiceTime;
    private Date customerDeliveryDate = new Date();
    private String courierType;
    private String courierId;
    private String manifestNumber;
    private String assignedHubCode;
    private String vehicleRegNumber;
    private String routeId;
    private String riderType;
    private Long deliveryAttemptCount;
    private String ndrId;
    private String ndrText;
    private Date deliveryTimeSlotStart;
    private Date deliveryTimeSlotEnd;
    private Date reScheduledSlotStart;
    private Date reScheduledSlotEnd;
    private Double invoiceAmount;
    private Double totalAmount;
    private String invoiceUrl;
    private String paymentLink;
    private String productCode;
    private String sequenceNo;
    private String actualSequenceNo;
    private String isCustomsDeclarable;
    private String sourceHubCode;
    private String destinationHubCode;
    private String destinationDetails;
    private String address;
    private String destinations;
    private String emailId;
    private String destCompanyName;
    private String name;
    private String phone;
    private String alternatePhone;
    private String addressLine1;
    private String addressLine2;
    private String pinCode;
    private String district;
    private String city;
    private String state;
    private String country;
    private Double latitude;
    private Double longitude;
    private String imageRefList;
    private Long deletionIndicator = 0L;
    private String receiverName;
    private Date deliveryDateTime;
    private String etaDateTime;
    private String receiverRelationShip;
    private String receiverPhone;
    private String invoiceName;
    private String chequeNo;
    private String paymentCollected;
    private Double cashCollected;
    private Double onlineCollected;
    private Double chequeCollected;
    private Double collectedAmount;
    private String signatureIssue;
    private String referenceField1;
    private String referenceField2;
    private String referenceField3;
    private String referenceField4;
    private String referenceField5;
    private String referenceField6;
    private String referenceField7;
    private String referenceField8;
    private String referenceField9;
    private String referenceField10;
    private String referenceField11;
    private String referenceField12;
    private String referenceField13;
    private String referenceField14;
    private String referenceField15;
    private String referenceField16;
    private String referenceField17;
    private String referenceField18;
    private String referenceField19;
    private String referenceField20;
    private String createdBy;
    private Date createdOn = new Date();
    private String updatedBy;
    private Date updatedOn = new Date();


}
