server.port=8089

#================================
# JPA
#================================
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true



#================================================
#database details for first datasource
#================================================
datasourceone.datasource.url=jdbc:mysql://localhost:3306/client_a
datasourceone.datasource.username=root
datasourceone.datasource.password=RAmi123*
datasourceone.datasource.driver-class-name=com.mysql.jdbc.Driver


#==================================================
#database details for second datasource
#==================================================
datasourcetwo.datasource.url=jdbc:mysql://localhost:3306/client_b
datasourcetwo.datasource.username=root
datasourcetwo.datasource.password=RAmi123*
datasourcetwo.datasource.driver-class-name=com.mysql.jdbc.Driver



