server.port=8086

server.servlet.context-path=/classicwms

#Dev
<<<<<<< HEAD
#spring.datasource.url=jdbc:sqlserver://3.111.134.239;databaseName=WMS_WK
#spring.datasource.username=sa
#spring.datasource.password=Do1cavIFK4^$pQ^zZYsX
=======
spring.datasource.url=jdbc:sqlserver://3.111.134.239;databaseName=WMS_WK
spring.datasource.username=sa
spring.datasource.password=Do1cavIFK4^$pQ^zZYsX
>>>>>>> 81dc64bb940937a238631ec1ef8d3af347b8ec9e

#UAT
#server.port=8786
#server.servlet.context-path=/walkaroo
<<<<<<< HEAD
spring.datasource.url=jdbc:sqlserver://13.203.34.203;databaseName=WMS_WK
spring.datasource.username=sa
spring.datasource.password=2iptDVoe6WZw3^()D4uKb
=======
#spring.datasource.url=jdbc:sqlserver://13.203.34.203;databaseName=WMS_WK
#spring.datasource.username=sa
#spring.datasource.password=2iptDVoe6WZw3^()D4uKb
>>>>>>> 81dc64bb940937a238631ec1ef8d3af347b8ec9e
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=false
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update

#-----------Batch Configurtion-------------------------------------
spring.batch.initialize-schema=always
spring.batch.job.enabled=false
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

#security
security.oauth2.resource.filter-order=3
