package com.tvhht.myapplication.putaway.model

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.google.gson.annotations.SerializedName
import kotlinx.android.parcel.Parcelize


@Parcelize
data class PutAwayCombineModel(
    @SerializedName("languageId") val languageId: String?=null,
    @SerializedName("companyCodeId") val companyCodeId: Int?=null,
    @SerializedName("plantId") val plantId: Int?=null,
    @SerializedName("warehouseId") val warehouseId: Int?=null,
    @SerializedName("preInboundNo") val preInboundNo: Int?=null,
    @SerializedName("refDocNumber") val refDocNumber: String?=null,
    @SerializedName("goodsReceiptNo") val goodsReceiptNo: Int?=null,
    @SerializedName("palletCode") val palletCode: Int?=null,
    @SerializedName("caseCode") val caseCode: Int?=null,
    @SerializedName("packBarcodes") val packBarcodes: Int?=null,
    @SerializedName("barcodeId") val barcodeId: String?=null,
    @SerializedName("inboundOrderTypeId") val inboundOrderTypeId: Int?=null,
    @SerializedName("putAwayNumber") val putAwayNumber: Int?=null,
    @SerializedName("proposedStorageBin") val proposedStorageBin: String?=null,
    @SerializedName("putAwayQuantity") val putAwayQuantity: Int?=null,
    @SerializedName("putAwayUom") val putAwayUom: String?=null,
    @SerializedName("strategyTypeId") val strategyTypeId: Int?=null,
    @SerializedName("strategyNo") val strategyNo: Int?=null,
    @SerializedName("proposedHandlingEquipment") val proposedHandlingEquipment: String?=null,
    @SerializedName("assignedUserId") val assignedUserId: String?=null,
    @SerializedName("statusId") val statusId: Int?=null,
    @SerializedName("quantityType") val quantityType: String?=null,
    @SerializedName("referenceField1") val referenceField1: String?=null,
    @SerializedName("referenceField2") val referenceField2: String?=null,
    @SerializedName("referenceField3") val referenceField3: String?=null,
    @SerializedName("referenceField4") val referenceField4: String?=null,
    @SerializedName("referenceField5") val referenceField5: String?=null,
    @SerializedName("referenceField6") val referenceField6: String?=null,
    @SerializedName("referenceField7") val referenceField7: String?=null,
    @SerializedName("referenceField8") val referenceField8: String?=null,
    @SerializedName("referenceField9") val referenceField9: String?=null,
    @SerializedName("referenceField10") val referenceField10: String?=null,
    @SerializedName("deletionIndicator") val deletionIndicator: Int?=null,
    @SerializedName("createdBy") val createdBy: String?=null,
    @SerializedName("createdOn") val createdOn: String?=null,
    @SerializedName("confirmedBy") val confirmedBy: String?=null,
    @SerializedName("confirmedOn") val confirmedOn: String?=null,
    @SerializedName("updatedBy") val updatedBy: String?=null,
    @SerializedName("updatedOn") val updatedOn: String?=null,
    @SerializedName("acceptedQty") val acceptedQty: Int?=null,
    @SerializedName("batchSerialNumber") val batchSerialNumber: String?=null,
    @SerializedName("businessPartnerCode") val businessPartnerCode: String?=null,
    @SerializedName("confirmedQty") val confirmedQty: Int?=null,
    @SerializedName("containerNo") val containerNo: String?=null,
    @SerializedName("crossDockAllocationQty") val crossDockAllocationQty: Int?=null,
    @SerializedName("damageQty") val damageQty: Int?=null,
    @SerializedName("expiryDate") val expiryDate: String?=null,
    @SerializedName("grUom") val grUom: String?=null,
    @SerializedName("hsnCode") val hsnCode: String?=null,
    @SerializedName("invoiceNo") val invoiceNo: String?=null,
    @SerializedName("itemBarcode") val itemBarcode: String?=null,
    @SerializedName("itemCode") val itemCode: String?=null,
    @SerializedName("itemDescription") val itemDescription: String?=null,
    @SerializedName("lineNo") val lineNo: Int?=null,
    @SerializedName("manufacturerDate") val manufacturerDate: String?=null,
    @SerializedName("manufacturerPartNo") val manufacturerPartNo: String?=null,
    @SerializedName("orderQty") val orderQty: Int?=null,
    @SerializedName("orderUom") val orderUom: String?=null,
    @SerializedName("putAwayHandlingEquipment") val putAwayHandlingEquipment: String?=null,
    @SerializedName("receiptQty") val receiptQty: Int?=null,
    @SerializedName("referenceOrderNo") val referenceOrderNo: String?=null,
    @SerializedName("referenceOrderQty") val referenceOrderQty: Int?=null,
    @SerializedName("remainingQty") val remainingQty: Int?=null,
    @SerializedName("remarks") val remarks: String?=null,
    @SerializedName("specialStockIndicatorId") val specialStockIndicatorId: Int?=null,
    @SerializedName("specificationActual") val specificationActual: String?=null,
    @SerializedName("stockTypeId") val stockTypeId: Int?=null,
    @SerializedName("storageMethod") val storageMethod: String?=null,
    @SerializedName("storageQty") val storageQty: Int?=null,
    @SerializedName("variantCode") val variantCode: Int?=null,
    @SerializedName("variantSubCode") val variantSubCode: String?=null,
    @SerializedName("variantType") val variantType: String?=null
    ) : Parcelable