package com.tvhht.myapplication.putaway.model

import com.google.gson.annotations.SerializedName


data class PutAwayMfrModel (
    @SerializedName("acceptedQty") val acceptedQty : Int?=null,
    @SerializedName("assignedUserId") val assignedUserId : String?=null,
    @SerializedName("batchSerialNumber") val batchSerialNumber : String?=null,
    @SerializedName("businessPartnerCode") val businessPartnerCode : String?=null,
    @SerializedName("caseCode") val caseCode : String?=null,
    @SerializedName("companyCodeId") val companyCodeId : String?=null,
    @SerializedName("confirmedBy") val confirmedBy : String?=null,
    @SerializedName("confirmedOn") val confirmedOn : String?=null,
    @SerializedName("confirmedQty") val confirmedQty : Int?=null,
    @SerializedName("containerNo") val containerNo : String?=null,
    @SerializedName("createdBy") val createdBy : String?=null,
    @SerializedName("createdOn") val createdOn : String?=null,
    @SerializedName("crossDockAllocationQty") val crossDockAllocationQty : Int?=null,
    @SerializedName("damageQty") val damageQty : Int?=null,
    @SerializedName("deletionIndicator") val deletionIndicator : Int?=null,
    @SerializedName("expiryDate") val expiryDate : String?=null,
    @SerializedName("goodsReceiptNo") val goodsReceiptNo : String?=null,
    @SerializedName("grUom") val grUom : String?=null,
    @SerializedName("hsnCode") val hsnCode : String?=null,
    @SerializedName("inboundOrderTypeId") val inboundOrderTypeId : Int?=null,
    @SerializedName("invoiceNo") val invoiceNo : String?=null,
    @SerializedName("itemBarcode") val itemBarcode : String?=null,
    @SerializedName("itemCode") val itemCode : String?=null,
    @SerializedName("itemDescription") val itemDescription : String?=null,
    @SerializedName("languageId") val languageId : String?=null,
    @SerializedName("lineNo") val lineNo : Int?=null,
    @SerializedName("manufacturerDate") val manufacturerDate : String?=null,
    @SerializedName("manufacturerPartNo") val manufacturerPartNo : String?=null,
    @SerializedName("orderQty") val orderQty : Int?=null,
    @SerializedName("orderUom") val orderUom : String?=null,
    @SerializedName("packBarcodes") val packBarcodes : String?=null,
    @SerializedName("palletCode") val palletCode : String?=null,
    @SerializedName("plantId") val plantId : String?=null,
    @SerializedName("preInboundNo") val preInboundNo : String?=null,
    @SerializedName("putAwayHandlingEquipment") val putAwayHandlingEquipment : String?=null,
    @SerializedName("quantityType") val quantityType : String?=null,
    @SerializedName("receiptQty") val receiptQty : Int?=null,
    @SerializedName("refDocNumber") val refDocNumber : String?=null,
    @SerializedName("referenceField1") val referenceField1 : String?=null,
    @SerializedName("referenceField10") val referenceField10 : String?=null,
    @SerializedName("referenceField2") val referenceField2 : String?=null,
    @SerializedName("referenceField3") val referenceField3 : String?=null,
    @SerializedName("referenceField4") val referenceField4 : String?=null,
    @SerializedName("referenceField5") val referenceField5 : String?=null,
    @SerializedName("referenceField6") val referenceField6 : String?=null,
    @SerializedName("referenceField7") val referenceField7 : String?=null,
    @SerializedName("referenceField8") val referenceField8 : String?=null,
    @SerializedName("referenceField9") val referenceField9 : String?=null,
    @SerializedName("referenceOrderNo") val referenceOrderNo : String?=null,
    @SerializedName("referenceOrderQty") val referenceOrderQty : Int?=null,
    @SerializedName("remainingQty") val remainingQty : Int?=null,
    @SerializedName("remarks") val remarks : String?=null,
    @SerializedName("specialStockIndicatorId") val specialStockIndicatorId : Int?=null,
    @SerializedName("specificationActual") val specificationActual : String?=null,
    @SerializedName("statusId") val statusId : Int?=null,
    @SerializedName("stockTypeId") val stockTypeId : Int?=null,
    @SerializedName("storageMethod") val storageMethod : String?=null,
    @SerializedName("storageQty") val storageQty : Int?=null,
    @SerializedName("updatedBy") val updatedBy : String?=null,
    @SerializedName("updatedOn") val updatedOn : String?=null,
    @SerializedName("variantCode") val variantCode : Int?=null,
    @SerializedName("variantSubCode") val variantSubCode : String?=null,
    @SerializedName("variantType") val variantType : String?=null,
    @SerializedName("warehouseId") val warehouseId : String?=null
)
