
#remote
server.port=8184
#server.port=8284
server.servlet.context-path=/classicwms/api/wms-transaction-service

spring.datasource.url=jdbc:sqlserver://3.111.134.239;databaseName=WMS_IMF
spring.datasource.username=sa
spring.datasource.password=Do1cavIFK4^$pQ^zZYsX
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=false
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.useServerPrepStmts=true
spring.datasource.hikari.data-source-properties.rewriteBatchedStatements=true
spring.datasource.hikari.minimumIdle=10
spring.datasource.hikari.maximumPoolSize=50
spring.datasource.hikari.idleTimeout=120000
spring.datasource.hikari.maxLifetime=500000

#datasourceone.datasource.url=jdbc:sqlserver://3.111.134.239;databaseName=WMS_WK
#datasourceone.datasource.username=sa
#datasourceone.datasource.password=Do1cavIFK4^$pQ^zZYsX
#datasourceone.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#datasourceone.jpa.show-sql=false
#datasourceone.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
#datasourceone.jpa.hibernate.ddl-auto=update

#datasourceone.datasource.hikari.data-source-properties.cachePrepStmts=true
#datasourceone.datasource.hikari.data-source-properties.useServerPrepStmts=true
#datasourceone.datasource.hikari.data-source-properties.rewriteBatchedStatements=true
#datasourceone.datasource.hikari.minimumIdle=10
#datasourceone.datasource.hikari.maximumPoolSize=50
#datasourceone.datasource.hikari.idleTimeout=120000
#datasourceone.datasource.hikari.maxLifetime=500000

#datasourcetwo.datasource.url=jdbc:sqlserver://3.111.134.239;databaseName=WMS_IMF
#datasourcetwo.datasource.username=sa
#datasourcetwo.datasource.password=Do1cavIFK4^$pQ^zZYsX
#datasourcetwo.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#datasourcetwo.jpa.show-sql=false
#datasourcetwo.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
#datasourcetwo.jpa.hibernate.ddl-auto=update

#datasourcetwo.datasource.hikari.data-source-properties.cachePrepStmts=true
#datasourcetwo.datasource.hikari.data-source-properties.useServerPrepStmts=true
#datasourcetwo.datasource.hikari.data-source-properties.rewriteBatchedStatements=true
#datasourcetwo.datasource.hikari.minimumIdle=10
#datasourcetwo.datasource.hikari.maximumPoolSize=50
#datasourcetwo.datasource.hikari.idleTimeout=120000
#datasourcetwo.datasource.hikari.maxLifetime=500000

#security
security.oauth2.resource.filter-order=3
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_updates=true