import { Injectable } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Injectable({
  providedIn: 'root',
})
export class FormService {
  constructor(private fb: FormBuilder) {}

  createForm(itemType: string): FormGroup {
    switch (itemType) {
      case 'sorting':
        return this.fb.group({
          uiProcessConfirm: [true, ],
          batchNumber: [],
          companyCodeId: [],
          companyDescription: [],
          bomItem:[],
          createdBy: [],
          createdOn: [],
          deletionIndicator: [],
          endTime: [],
          impurities: [],
          itemCode: [],
          itemDescription: [],
          itemType: [],
          languageDescription: [],
          languageId: [],
          noOfWorkers: [],
          operationDetail: [],
          operationNumber: [],
          outputQty: [],
          phaseDescription: [],
          phaseNumber:[],
          phaseId: [],
          plantDescription: [],
          plantId: [],
          processQty: [],
          productionOrderLineNo: [],
          productionOrderNo: [],
          receipeId: [],
          referenceBatchNumber: [],
          referenceField1:[],
          referenceOrderNumber: [],
          startTime: [],
          statusDescription: [],
          statusId: [],
          supervisorName: [],
          updatedBy: [],
          updatedOn: [],
          warehouseDescription: [],
          warehouseId: [],
        });
      case 'soaking':
        return this.fb.group({
          uiProcessConfirm: [true, ],
          companyCodeId: [],
          companyDescription: [],
          createdBy: [],
          createdOn: [],
          bomItem:[],
          deletionIndicator: [],
          endTime: [],
          itemCode: [],
          itemDescription: [],
          itemType: [],
          batchNumber: [],
          languageDescription: [],
          languageId: [],
          noOfWorkers: [],
          operationDetail: [],
          operationNumber: [],
          operationDescription:[],
          outputQuantity: [],
          phaseDetail: [],
          phaseId: [],
          phaseNumber:[],
          plantDescription: [],
          phaseDescription:[],
          plantId: [],
          productionOrderLineNo: [],
          productionOrderNo: [],
          receipeId: [],
          referenceBatchNumber: [],
          referenceOrderNumber: [],
          referenceField1:[],
          roomTemperature: [],
          soakingQuantity: [],
          startTime: [],
          statusDescription: [],
          statusId: [],
          supervisorName: [],
          updatedBy: [],
          updatedOn: [],
          warehouseDescription: [],
          warehouseId: [],
          waterQuantity: [],
          waterTemperature: [],
        });
      case 'peeling':
        return this.fb.group({
          uiProcessConfirm: [true, ],
          batchNumber: [],
          boilingEndTime: [],
          boilingStartTime: [],
          brixOfBoiledDal: [],
          companyCodeId: [],
          companyDescription: [],
          bomItem:[],
          createdBy: [],
          createdOn: [],
          deletionIndicator: [],
          itemCode: [],
          itemDescription: [],
          itemType: [],
          languageDescription: [],
          languageId: [],
          noOfWorkers: [],
          operationDetail: [],
          operationNumber: [],
          operationDescription:[],
          peelingEndTime: [],
          peelingStartTime: [],
          phaseDetail: [],
          phaseId: [],
          phaseNumber:[],
          plantDescription: [],
          plantId: [],
          phaseDescription:[],
          postBoilingWeight: [],
          productionOrderLineNo: [],
          productionOrderNo: [],
          receipeId: [],
          referenceBatchNumber: [],
          referenceField1: [],
          referenceField10: [],
          referenceField2: [],
          referenceField3: [],
          referenceField4: [],
          referenceField5: [],
          referenceField6: [],
          referenceField7: [],
          referenceField8: [],
          referenceField9: [],
          referenceOrderNumber: [],
          statusDescription: [],
          statusId: [],
          supervisorName: [],
          updatedBy: [],
          updatedOn: [],
          warehouseDescription: [],
          warehouseId: [],
          washingEndTime: [],
          washingStartTime: [],
        });
      case 'paste':
        return this.fb.group({
          uiProcessConfirm: [true, ],
          batchNumber: [],
          boilingEndTime: [],
          boilingStartTime: [],
          companyCodeId: [],
          companyDescription: [],
          createdBy: [],
          bomItem:[],
          createdOn: [],
          deletionIndicator: [],
          issuedQuantity: [],
          itemCode: [],
          itemDescription: [],
          itemType: [],
          languageDescription: [],
          languageId: [],
          noOfWorkers: [],
          operationDetail: [],
          operationNumber: [],
          operationDescription:[],
          outputQuantity: [],
          pasteEndTime: [],
          pasteStartTime: [],
          phaseDetail: [],
          phaseId: [],
          plantDescription: [],
          phaseNumber:[],
          phaseDescription:[],
          plantId: [],
          postBoilingWeight: [],
          productionOrderLineNo: [],
          productionOrderNo: [],
          receipeId: [],
          referenceBatchNumber: [],
          referenceOrderNumber: [],
          referenceField1:[],
          statusDescription: [],
          statusId: [],
          storageLocation: [],
          supervisorName: [],
          updatedBy: [],
          updatedOn: [],
          warehouseDescription: [],
          warehouseId: [],
          waterQuantity: [],
        });
      case 'powder':
        return this.fb.group({
          uiProcessConfirm: [true, ],
          batchNumber: [],
          companyCodeId: [],
          companyDescription: [],
          createdBy: [],
          bomItem:[],
          createdOn: [],
          deletionIndicator: [],
          issuedQuantity: [],
          itemCode: [],
          itemDescription: [],
          itemType: [],
          languageId: [],
          numberOfWorkers: [],
          operationDetail: [],
          operationNumber: [],
          outputQuantity: [],
          operationDescription:[],
          referenceField1:[],
          phaseDescription: [],
          phaseId: [],
          phaseNumber:[],
          plantDescription: [],
          plantId: [],
          postRoastingWeight: [],
          powderPreparationEndTime: [],
          powderPreparationStartTime: [],
          productionOrderLineNo: [],
          productionOrderNo: [],
          receipeId: [],
          referenceBatchNumber: [],
          referenceOrderNumber: [],
          roastingEndTime: [],
          roastingStartTime: [],
          statusDescription: [],
          statusId: [],
          storageLocation: [],
          supervisorName: [],
          updatedBy: [],
          updatedOn: [],
          warehouseDescription: [],
          warehouseId: [],
        });
      case 'chopping':
        return this.fb.group({
          uiProcessConfirm: [true, ],
          batchNumber: [],
          companyCodeId: [],
          companyDescription: [],
          bomItem:[],
          createdBy: [],
          createdOn: [],
          deletionIndicator: [],
          endTime: [],
          issuedQuantity: [],
          itemCode: [],
          itemDescription: [],
          itemType: [],
          languageId: [],
          numberOfWorkers: [],
          operationDetail: [],
          operationNumber: [],
          operationDescription:[],
          outputQuantity: [],
          phaseDescription: [],
          phaseId: [],
          plantDescription: [],
          plantId: [],
          phaseNumber:[],
          productionOrderLineNo: [],
          productionOrderNo: [],
          receipeId: [],
          referenceBatchNumber: [],
          referenceOrderNumber: [],
          referenceField1:[],
          startTime: [],
          statusDescription: [],
          statusId: [],
          storageLocation: [],
          supervisorName: [],
          updatedBy: [],
          updatedOn: [],
          warehouseDescription: [],
          warehouseId: [],
        });
      case 'cooking':
        return this.fb.group({
          uiProcessConfirm: [true, ],
          batchNumber: [],
          beProcessConfirm: [],
          companyCodeId: [],
          bomItem:[],
          companyDescription: [],
          cookingEndTime: [],
          cookingStartTime: [],
          createdBy: [],
          createdOn: [],
          deletionIndicator: [],
          firstPacketTemperatureDuringRetortLoading: [],
          itemCode: [],
          itemDescription: [],
          itemType: [],
          languageId: [],
          numberOfWorkers: [],
          operationDetail: [],
          operationNumber: [],
          operationDescription:[],
          outputQuantity: [],
          packingEndTime: [],
          packingStartTime: [],
          phaseDescription: [],
          phaseId: [],
          phaseNumber:[],
          plantDescription: [],
          plantId: [],
          productionOrderLineNo: [],
          productionOrderNo: [],
          receipeId: [],
          referenceBatchNumber: [],
          referenceOrderNumber: [],
          referenceField1:[],
          retortEndTime: [],
          retortStartTime: [],
          statusDescription: [],
          statusId: [],
          supervisorName: [],
          updatedBy: [],
          updatedOn: [],
          warehouseDescription: [],
          warehouseId: [],
        });
      case 'QC Packing':
        return this.fb.group({
          uiProcessConfirm: [true, ],
          acidity: [],
          batchNumber: [],
          bostwickValue: [],
          color: [],
          companyCodeId: [],
          companyDescription: [],
          createdBy: [],
          createdOn: [],
          deletionIndicator: [],
          itemCode: [],
          itemDescription: [],
          itemType: [],
          languageId: [],
          moisture: [],
          numberOfWorkers: [],
          observation: [],
          operationDetail: [],
          operationNumber: [],
          outputQuantity: [],
          ph: [],
          phaseDescription: [],
          phaseId: [],
          plantDescription: [],
          plantId: [],
          productionOrderLineNo: [],
          productionOrderNo: [],
          receipeId: [],
          referenceBatchNumber: [],
          referenceOrderNumber: [],
          salt: [],
          statusDescription: [],
          statusId: [],
          sugarSyrupTss: [],
          supervisorName: [],
          temperature: [],
          tss: [],
          updatedBy: [],
          updatedOn: [],
          warehouseDescription: [],
          warehouseId: [],
        });
      case 'fgPacking':
        return this.fb.group({
          uiProcessConfirm: [true, ],
          batchNumber: [],
          companyCodeId: [],
          companyDescription: [],
          createdBy: [],
          createdOn: [],
          damagedPacketsInKg: [],
          deletionIndicator: [],
          itemCode: [],
          itemDescription: [],
          itemType: [],
          labTestingQuantity: [],
          languageDescription: [],
          languageId: [],
          noOfWorkers: [],
          notPassingThroughMetalDetector: [],
          operationDetail: [],
          operationNumber: [],
          phaseDetail: [],
          phaseId: [],
          physicalQuantity: [],
          plantDescription: [],
          plantId: [],
          productionOrderLineNo: [],
          productionOrderNo: [],
          receipeId: [],
          referenceBatchNumber: [],
          referenceOrderNumber: [],
          statusDescription: [],
          statusId: [],
          supervisorName: [],
          updatedBy: [],
          updatedOn: [],
          warehouseDescription: [],
          warehouseId: [],
        });
      case 'FG Delivery':
        return this.fb.group({
          uiProcessConfirm: [true, ],
          batchNumber: [],
          companyCodeId: [],
          createdBy: [],
          createdOn: [],
          customerName: [],
          deletionIndicator: [],
          dispatchQuantity: [],
          itemCode: [],
          itemDescription: [],
          itemType: [],
          languageId: [],
          operationDetail: [],
          operationNumber: [],
          orderQuantity: [],
          phaseDescription: [],
          phaseId: [],
          plantId: [],
          productionOrderLineNo: [],
          productionOrderNo: [],
          receipeId: [],
          referenceBatchNumber: [],
          referenceOrderNumber: [],
          statusDescription: [],
          statusId: [],
          transportDetails: [],
          updatedBy: [],
          updatedOn: [],
          warehouseId: [],
        });
      default:
        return this.fb.group({
          uiProcessConfirm: [true, ],
        });
    }
  }
}

// createForm(itemTypes: string[]): FormGroup[] {
//   return itemTypes.map(itemType => {

//   })
