package com.tekclover.wms.core.model.transaction;

import lombok.Data;
import java.util.Date;

@Data
public class PeriodicZeroStockLine {

	private String languageId;
	private String companyCode;
	private String plantId;
	private String warehouseId;
	private String cycleCountNo;
	private String itemCode;
	private String manufacturerName;
	private String storageBin;
	private Long lineNo;
	private String packBarcodes;
	private String itemDesc;
	private String manufacturerPartNo;
	private Long variantCode;
	private String variantSubCode;
	private String batchSerialNumber;
	private Long stockTypeId;
	private String specialStockIndicator;
	private String storageSectionId;
	private Double inventoryQuantity;
	private String inventoryUom;
	private Double countedQty;
	private Double varianceQty;
	private String cycleCounterId;
	private String cycleCounterName;
	private Long statusId;
	private String cycleCountAction;
	private String referenceNo;
	private Long approvalProcessId;
	private String approvalLevel;
	private String approverCode;
	private String approvalStatus;
	private String remarks;
	private String referenceField1;
	private String referenceField2;
	private String referenceField3;
	private String referenceField4;
	private String referenceField5;
	private String referenceField6;
	private String referenceField7;
	private String referenceField8;
	private String referenceField9;
	private String referenceField10;
	private Long deletionIndicator;
	private String createdBy;
	private Date createdOn = new Date();
	private String confirmedBy;
	private Date confirmedOn;
	private String countedBy;
	private Date countedOn;
	private String companyDescription;
	private String plantDescription;
	private String warehouseDescription;
	private String statusDescription;
	private String manufacturerCode;
	private String barcodeId;
	private String middlewareId;
	private String middlewareHeaderId;
	private String middlewareTable;
	private String manufacturerFullName;
	private String referenceDocumentType;
	private Double frozenQty;
	private Double inboundQuantity;
	private Double outboundQuantity;
	private Double firstCountedQty;
	private Double secondCountedQty;
	private String levelId;
	private Double amsVarianceQty;
}