-- Master Scripts

USE WMS;

-- BOM HEADER Table
CREATE TABLE `WMS`.`tblbomheader` (
  
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`PAR_ITM_CODE` NVARCHAR(50) NOT NULL,
	`BOM_NO` INTEGER NULL,
	`PAR_ITM_QTY` DECIMAL(30,4) NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,
	
  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `PAR_ITM_CODE`))
COMMENT = 'BOM HEADER';


-- BOM LINE Table
CREATE TABLE `WMS`.`tblbomline` (
	
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`BOM_NO` INTEGER NOT NULL,
	`CHL_ITEM_CODE` NVARCHAR(50) NOT NULL,
	`CHL_ITM_QTY` DECIMAL(30,4) NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `BOM_NO`, `CHL_ITEM_CODE`))
COMMENT = 'BOM LINE';

-- IM BASIC DATA1 Table
CREATE TABLE `WMS`.`tblimbasicdata1` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `C_ID` NVARCHAR(50) NOT NULL,
  `PLANT_ID` NVARCHAR(50) NOT NULL,
  `WH_ID` NVARCHAR(50) NOT NULL,
  `ITM_CODE` NVARCHAR(50) NOT NULL, 
  `UOM_ID` NVARCHAR(10) NOT NULL,
  `TEXT` NVARCHAR(500) NULL,
  `Model` NVARCHAR(50) NULL,
  `SPEC_01` NVARCHAR(200) NULL,
  `SPEC_02` NVARCHAR(200) NULL,
  `EAN_UPC_NO` NVARCHAR(200) NULL,
  `MFR_PART` NVARCHAR(200) NULL,
  `HSN_CODE` NVARCHAR(50) NULL,  
  `ITM_TYP_ID` INTEGER NULL,
  `ITM_GRP_ID` INTEGER NULL,
  `SUB_ITM_GRP_ID` INTEGER NULL,
  `ST_SEC_ID` NVARCHAR(10) NULL,
  `TOT_STK` DECIMAL(30,4) NULL,
  `MIN_STK` DECIMAL(30,4) NULL,
  `MAX_STK` DECIMAL(30,4) NULL,  
  `RE_ORD_LVL` DECIMAL(30,4) NULL,
  `REP_QTY` DECIMAL(30,4) NULL,
  `SAFTY_STCK` DECIMAL(30,4) NULL,
  `STATUS_ID` INTEGER NULL,
  `REF_FIELD_1` NVARCHAR(200) NULL,
  `REF_FIELD_2` NVARCHAR(200) NULL,
  `REF_FIELD_3` NVARCHAR(200) NULL,
  `REF_FIELD_4` NVARCHAR(200) NULL,
  `REF_FIELD_5` NVARCHAR(200) NULL,
  `REF_FIELD_6` NVARCHAR(200) NULL,
  `REF_FIELD_7` NVARCHAR(200) NULL,
  `REF_FIELD_8` NVARCHAR(200) NULL,
  `REF_FIELD_9` NVARCHAR(200) NULL,
  `REF_FIELD_10` NVARCHAR(200) NULL,
  `IS_DELETED` INTEGER NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `C_ID`, `PLANT_ID`, `WH_ID`, `ITM_CODE`, `LANG_ID`, `UOM_ID`))
COMMENT = 'IM BASIC DATA1';


-- IM BASIC DATA2 Table
CREATE TABLE `WMS`.`tblimbasicdata2` (
	
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`ITM_CODE` NVARCHAR(50) NOT NULL,
	`ITM_BARCODE` NVARCHAR(50) NULL,
	`LENGTH` DECIMAL(30,4) NULL,
	`WITDH` DECIMAL(30,4) NULL,
	`HEIGHT` DECIMAL(30,4) NULL,
	`DIM_UOM` NVARCHAR(50) NULL,
	`VOLUME` DECIMAL(30,4) NULL,
	`VOL_UOM` NVARCHAR(50) NULL,
	`QPC_01` DECIMAL(30,4) NULL,
	`QPC_02` DECIMAL(30,4) NULL,
	`UNIT_PR` DECIMAL(30,2) NULL,
	`CURR_ID` INTEGER NULL,
	`GR_WT` DECIMAL(30,4) NULL,
	`NT_WT` DECIMAL(30,4) NULL,
	`WT_UOM` NVARCHAR(50) NULL,
	`PREF_ST_BIN` NVARCHAR(50) NULL,
	-- `IMAGE` OBJECT NULL,
	`IT_CL` NVARCHAR(50) NULL,
	`CROSS_DK_IND` BOOLEAN NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,
  
  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `ITM_CODE`))
COMMENT = 'IM BASIC DATA2';


-- IM STRATEGIES Table
CREATE TABLE `WMS`.`tblimstrategies` (
  
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`ITM_CODE` NVARCHAR(50) NOT NULL,
	`STR_TYP_ID` NVARCHAR(50) NOT NULL,
	`SEQ_IND` INTEGER NOT NULL,
	`CAP_CHK` BOOLEAN NULL,
	`PREF_ST_BIN` NVARCHAR(50) NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `ITM_CODE`, `STR_TYP_ID`, `SEQ_IND`))
COMMENT = 'IM STRATEGIES';


-- IM ALTERNATE UOM Table
CREATE TABLE `WMS`.`tblimalternateuom` (
 	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`ITM_CODE` NVARCHAR(50) NOT NULL,
	`UOM_ID` NVARCHAR(10) NOT NULL,
	`ALT_UOM` NVARCHAR(50) NOT NULL,
	`S_NO` INTEGER NULL,
	`FRM_UNT` INTEGER NULL,
	`TO_UNT` INTEGER NULL,
	`QPC_01` DECIMAL(30,4) NULL,
	`QPC_02` DECIMAL(30,4) NULL,
	`ALT_UOM_BAR` NVARCHAR(50) NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL, 
  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `ITM_CODE`, `UOM_ID`, `ALT_UOM`))
COMMENT = 'IM ALTERNATE UOM';


-- IM PARTNER Table
CREATE TABLE `WMS`.`tblimpartner` (
	
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`ITM_CODE` NVARCHAR(50) NOT NULL,
	`PARTNER_TYP` NVARCHAR(50) NOT NULL,
	`PARTNER_CODE` NVARCHAR(50) NOT NULL,
	`PARTNER_ITM_CODE` NVARCHAR(200) NULL,
	`PARTNER_ITM_BAR` NVARCHAR(50) NULL,
	`MFR_BAR` NVARCHAR(200) NULL,
	`BRND_NM` NVARCHAR(200) NULL,
	`STK` DECIMAL(30,4) NULL,
	`STK_UOM` NVARCHAR(50) NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

  
  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `ITM_CODE`, `PARTNER_TYP`, `PARTNER_CODE`))
COMMENT = 'IM PARTNER';


-- IM PACKING Table
CREATE TABLE `WMS`.`tblimpacking` (
  
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`ITM_CODE` NVARCHAR(50) NOT NULL,
	`PACK_MAT_NO` NVARCHAR(50) NOT NULL,
	`PACK_IND` BOOLEAN NULL,
	`PACK_MAT_TEXT` NVARCHAR(500) NULL,
	`PACK_QTY` DECIMAL(30,4) NULL,
	`REQ_SHRNK` BOOLEAN NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

  
  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `ITM_CODE`,  `PACK_MAT_NO` ))
COMMENT = 'IM PACKING';


-- STORAGE BIN Table
CREATE TABLE `WMS`.`tblstoragebin` (
 
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`ST_BIN` NVARCHAR(50) NOT NULL,
	`FL_ID` INTEGER NULL,
	`ST_SEC_ID` NVARCHAR(10) NULL,
	`ROW_ID` NVARCHAR(10) NULL,
	`AISLE_ID` NVARCHAR(10) NULL,
	`SPAN_ID` NVARCHAR(10) NULL,
	`SHELF_ID` NVARCHAR(10) NULL,
	`BIN_SECTION_ID` INTEGER NULL,
	`ST_TYP_ID` INTEGER NULL,
	`BIN_CL_ID` INTEGER NULL,
	`ST_BIN_TEXT` NVARCHAR(500) NULL,
	`BIN_BAR` NVARCHAR(50) NULL,
	`PUTAWAY_BLOCK` BOOLEAN NULL,
	`PICK_BLOCK` BOOLEAN NULL,
	`BLK_REASON` NVARCHAR(500) NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `ST_BIN` ))
COMMENT = 'STORAGE BIN';


-- HANDLING EQUIPMENT Table
CREATE TABLE `WMS`.`tblhandlingequipment` (
  
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`HE_ID` NVARCHAR(50) NOT NULL,
	`CATEGORY` NVARCHAR(50) NULL,
	`HU_UNIT` NVARCHAR(50) NULL,
	`AQU_DT` DATE NULL,
	`AQU_VAL` DECIMAL(30,4) NULL,
	`CURR_ID` INTEGER NULL,
	`MOD_NO` NVARCHAR(200) NULL,
	`MFR_PART` NVARCHAR(200) NULL,
	`CTY_ORG` NVARCHAR(50) NULL,
	`HE_BAR` NVARCHAR(50) NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

  
  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `HE_ID` ))
COMMENT = 'HANDLING EQUIPMENT';


-- HANDLING UNIT Table
CREATE TABLE `WMS`.`tblhandlingunit` (
 
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`HU_UNIT` NVARCHAR(50) NOT NULL,
	`LENGTH` DECIMAL(30,4) NULL,
	`LEN_UOM` NVARCHAR(50) NULL,
	`WIDTH` DECIMAL(30,4) NULL,
	`WID_UOM` NVARCHAR(50) NULL,
	`HGT` DECIMAL(30,4) NULL,
	`HGT_UOM` NVARCHAR(50) NULL,
	`VOLUME` DECIMAL(30,4) NULL,
	`VOL_UOM` NVARCHAR(50) NULL,
	`WEIGHT` DECIMAL(30,4) NULL,
	`WT_UOM` NVARCHAR(50) NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

  
  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `HU_UNIT` ))
COMMENT = 'HANDLING UNIT';


-- BOM Table
CREATE TABLE `WMS`.`tblbomid` (

	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`PAR_ITM_CODE` NVARCHAR(50) NOT NULL,
	`CHL_ITEM_CODE` NVARCHAR(50) NOT NULL,
	`PAR_ITM_QTY` DECIMAL(30,4) NULL,
	`CHL_ITM_QTY` DECIMAL(30,4) NULL,
	`NEW_VL` NVARCHAR(50) NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

  
  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `PAR_ITM_CODE`, `CHL_ITEM_CODE` ))
COMMENT = 'BOM';


-- BUSINESS PARTNER Table
CREATE TABLE `WMS`.`tblbusinesspartner` (
  
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`PARTNER_TYP` INTEGER NOT NULL,
	`PARTNER_CODE` NVARCHAR(50) NOT NULL,
	`PARTNER_NM` NVARCHAR(50) NULL,
	`ADD_1` NVARCHAR(5000) NULL,
	`ADD_2` NVARCHAR(5000) NULL,
	`ZONE` NVARCHAR(500) NULL,
	`COUNTRY` NVARCHAR(50) NULL,
	`STATE` NVARCHAR(50) NULL,
	`PH_NO` NVARCHAR(500) NULL,
	`FX_NO` NVARCHAR(500) NULL,
	`MAIL_ID` NVARCHAR(500) NULL,
	`REF_TXT` NVARCHAR(500) NULL,
	`LOCATION` NVARCHAR(500) NULL,
	`LATITUDE` DECIMAL(30,15) NULL,
	`LONGITUDE` DECIMAL(30,15) NULL,
	`ST_TYP_ID` INTEGER NULL,
	`ST_BIN` NVARCHAR(50) NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

  
  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `PARTNER_TYP`, `PARTNER_CODE` ))
COMMENT = 'BUSINESS PARTNER';


-- PACKING MATERIAL Table
CREATE TABLE `WMS`.`tblpackingmaterial` (
  
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`PACK_MAT_NO` NVARCHAR(50) NOT NULL,
	`PACK_MAT_TEXT` NVARCHAR(500) NULL,
	`LENTGH` DECIMAL(30,4) NULL,
	`WIDTH` DECIMAL(30,4) NULL,
	`HEIGHT` DECIMAL(30,4) NULL,
	`DIM_UOM` NVARCHAR(50) NULL,
	`VOLUME` DECIMAL(30,4) NULL,
	`VOL_UOM` NVARCHAR(50) NULL,
	`PARTNER_CODE` NVARCHAR(50) NULL,
	`TOT_STOCK` DECIMAL(30,4) NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`IS_DELETED` INTEGER NULL,
	`CTD_BY` NVARCHAR(50) NULL,
	`CTD_ON` DATETIME NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

  
  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID`, `PACK_MAT_NO`))
COMMENT = 'PACKING MATERIAL';


-- AUDIT LOG Table
CREATE TABLE `WMS`.`tblauditlogid` (
  
	`LANG_ID` NVARCHAR(5) NOT NULL,
	`C_ID` NVARCHAR(50) NOT NULL,
	`PLANT_ID` NVARCHAR(50) NOT NULL,
	`WH_ID` NVARCHAR(50) NOT NULL,
	`AUD_FILE_NO` NVARCHAR(20) NULL,
	`FISCAL YEAR` INTEGER NULL,
	`OBJ_NM` NVARCHAR(50) NULL,
	`SCREEN_NO` NVARCHAR(10) NULL,
	`SUB_SCREEN_NO` NVARCHAR(10) NULL,
	`TABLE_NM` NVARCHAR(50) NULL,
	`MOD_FIELD` NVARCHAR(50) NULL,
	`OLD_VL` NVARCHAR(50) NULL,
	`NEW_VL` NVARCHAR(50) NULL,
	`STATUS_ID` INTEGER NULL,
	`REF_FIELD_1` NVARCHAR(200) NULL,
	`REF_FIELD_2` NVARCHAR(200) NULL,
	`REF_FIELD_3` NVARCHAR(200) NULL,
	`REF_FIELD_4` NVARCHAR(200) NULL,
	`REF_FIELD_5` NVARCHAR(200) NULL,
	`REF_FIELD_6` NVARCHAR(200) NULL,
	`REF_FIELD_7` NVARCHAR(200) NULL,
	`REF_FIELD_8` NVARCHAR(200) NULL,
	`REF_FIELD_9` NVARCHAR(200) NULL,
	`REF_FIELD_10` NVARCHAR(200) NULL,
	`UTD_BY` NVARCHAR(50) NULL,
	`UTD_ON` DATETIME NULL,

  PRIMARY KEY ( `LANG_ID`, `C_ID`, `PLANT_ID`, `WH_ID` ))
COMMENT = 'AUDIT LOG';