
#remote
<<<<<<< HEAD
server.port=9192
server.servlet.context-path=/almailem/api/alm-connector-service

spring.datasource.url=jdbc:sqlserver://10.20.1.96;databaseName=ALMCONN_DEV
spring.datasource.username=sa
spring.datasource.password=wms@123456
=======
server.port=9191
server.servlet.context-path=/almailem/api/alm-connector-service

spring.datasource.url=jdbc:sqlserver://localhost;databaseName=WMS_ALMDEV
spring.datasource.username=sa
spring.datasource.password=root
>>>>>>> 81dc64bb940937a238631ec1ef8d3af347b8ec9e
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=false
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.useServerPrepStmts=true
spring.datasource.hikari.data-source-properties.rewriteBatchedStatements=true

<<<<<<< HEAD
=======

#----------------Spring - Mongo Configuration----------------------
#spring.data.mongodb.host=35.154.84.178
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=WMS
#spring.autoconfigure.exclude= \
#  org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,\
#  org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

>>>>>>> 81dc64bb940937a238631ec1ef8d3af347b8ec9e
#security
security.oauth2.resource.filter-order=3
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_updates=true