package com.tvhht.myapplication.putaway.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.google.gson.annotations.SerializedName

@Entity
data class PutAwaySubmit(
    @PrimaryKey(autoGenerate = true) val putAwayID: Int? = null,
    @SerializedName("languageId") var languageId: String? = null,
    @SerializedName("companyCode") var companyCode: String? = null,
    @SerializedName("plantId") var plantId: String? = null,
    @SerializedName("warehouseId") var warehouseId: String? = null,
    @SerializedName("preInboundNo") var preInboundNo: String? = null,
    @SerializedName("refDocNumber") var refDocNumber: String? = null,
    @SerializedName("goodsReceiptNo") var goodsReceiptNo: String? = null,
    @SerializedName("palletCode") var palletCode: String? = null,
    @SerializedName("caseCode") var caseCode: String? = null,
    @SerializedName("packBarcodes") var packBarcodes: String? = null,
    @SerializedName("lineNo") var lineNo: Int? = null,
    @SerializedName("itemCode") var itemCode: String? = null,
    @SerializedName("inboundOrderTypeId") var inboundOrderTypeId: Int? = null,
    @SerializedName("variantCode") var variantCode: String? = null,
    @SerializedName("variantSubCode") var variantSubCode: String? = null,
    @SerializedName("batchSerialNumber") var batchSerialNumber: String? = null,
    @SerializedName("stockTypeId") var stockTypeId: Int? = null,
    @SerializedName("specialStockIndicatorId") var specialStockIndicatorId: Int? = null,
    @SerializedName("storageMethod") var storageMethod: String? = null,
    @SerializedName("statusId") var statusId: Int? = null,
    @SerializedName("businessPartnerCode") var businessPartnerCode: String? = null,
    @SerializedName("containerNo") var containerNo: String? = null,
    @SerializedName("invoiceNo") var invoiceNo: String? = null,
    @SerializedName("itemDescription") var itemDescription: String? = null,
    @SerializedName("manufacturerPartNo") var manufacturerPartNo: String? = null,
    @SerializedName("hsnCode") var hsnCode: String? = null,
    @SerializedName("variantType") var variantType: String? = null,
    @SerializedName("specificationActual") var specificationActual: String? = null,
    @SerializedName("itemBarcode") var itemBarcode: String? = null,
    @SerializedName("orderQty") var orderQty: Int? = null,
    @SerializedName("orderUom") var orderUom: String? = null,
    @SerializedName("receiptQty") var receiptQty: String? = null,
    @SerializedName("grUom") var grUom: String? = null,
    @SerializedName("acceptedQty") var acceptedQty: Int? = null,
    @SerializedName("damageQty") var damageQty: Int? = null,
    @SerializedName("quantityType") var quantityType: String? = null,
    @SerializedName("assignedUserId") var assignedUserId: String? = null,
    @SerializedName("putAwayHandlingEquipment") var putAwayHandlingEquipment: String? = null,
    @SerializedName("confirmedQty") var confirmedQty: String? = null,
    @SerializedName("remainingQty") var remainingQty: String? = null,
    @SerializedName("referenceOrderNo") var referenceOrderNo: String? = null,
    @SerializedName("referenceOrderQty") var referenceOrderQty: String? = null,
    @SerializedName("crossDockAllocationQty") var crossDockAllocationQty: String? = null,
    @SerializedName("manufacturerDate") var manufacturerDate: String? = null,
    @SerializedName("expiryDate") var expiryDate: String? = null,
    @SerializedName("storageQty") var storageQty: String? = null,
    @SerializedName("remarks") var remarks: String? = null,
    @SerializedName("cbmUnit") var cbmUnit: String? = null,
    @SerializedName("referenceField1") var referenceField1: String? = null,
    @SerializedName("referenceField2") var referenceField2: String? = null,
    @SerializedName("referenceField3") var referenceField3: String? = null,
    @SerializedName("referenceField4") var referenceField4: String? = null,
    @SerializedName("referenceField5") var referenceField5: String? = null,
    @SerializedName("referenceField6") var referenceField6: String? = null,
    @SerializedName("referenceField7") var referenceField7: String? = null,
    @SerializedName("referenceField8") var referenceField8: String? = null,
    @SerializedName("referenceField9") var referenceField9: String? = null,
    @SerializedName("referenceField10") var referenceField10: String? = null,
    @SerializedName("deletionIndicator") var deletionIndicator: Int? = null,
    @SerializedName("createdBy") var createdBy: String? = null,
    @SerializedName("createdOn") var createdOn: String? = null,
    @SerializedName("updatedBy") var updatedBy: String? = null,
    @SerializedName("updatedOn") var updatedOn: String? = null,
    @SerializedName("confirmedBy") var confirmedBy: String? = null,
    @SerializedName("confirmedOn") var confirmedOn: String? = null,
    @SerializedName("inventoryQuantity") var inventoryQuantity: Double? = null,
    @SerializedName("barcodeId") var barcodeId: String? = null,
    @SerializedName("cbm") var cbm: Int? = null,
    @SerializedName("manufacturerCode") var manufacturerCode: String? = null,
    @SerializedName("manufacturerName") var manufacturerName: String? = null,
    @SerializedName("origin") var origin: String? = null,
    @SerializedName("brand") var brand: String? = null,
    @SerializedName("rejectType") var rejectType: String? = null,
    @SerializedName("rejectReason") var rejectReason: String? = null,
    @SerializedName("cbmQuantity") var cbmQuantity: Int? = null,
    @SerializedName("companyDescription") var companyDescription: String? = null,
    @SerializedName("plantDescription") var plantDescription: String? = null,
    @SerializedName("warehouseDescription") var warehouseDescription: String? = null,
    @SerializedName("statusDescription") var statusDescription: String? = null,
    @SerializedName("interimStorageBin") var interimStorageBin: String? = null,
    @SerializedName("middlewareId") var middlewareId: String? = null,
    @SerializedName("middlewareTable") var middlewareTable: String? = null,
    @SerializedName("manufactureFullName") var manufactureFullName: String? = null,
    @SerializedName("middlewareHeaderId") var middlewareHeaderId: String? = null,
    @SerializedName("purchaseOrderNumber") var purchaseOrderNumber: String? = null,
    @SerializedName("referenceDocumentType") var referenceDocumentType: String? = null,
    @SerializedName("confirmedStorageBin") var confirmedStorageBin: String? = null,
    @SerializedName("putawayConfirmedQty") var putawayConfirmedQty: Double? = null,
    @SerializedName("proposedStorageBin") var proposedStorageBin: String? = null,
    @SerializedName("putAwayNumber") var putAwayNumber: String? = null
)